In [87]:
import pandas as pd
import os
import glob

# Specify the path to your folder containing CSV files
folder_path = 'StudentProficiencyData'

# Use glob to get a list of all CSV files in the folder
file_pattern = os.path.join(folder_path, '*.csv.gz')
file_list = glob.glob(file_pattern)

# Initialize an empty DataFrame to concatenate the individual files
df_list = []

column_names = ['studentid', 'previousitems', 'itemdifficulty', 'currentperformance', 'currentscore', 'itemid', 'eventtime', 'skillid', 'subskillid']

# Loop through each file and load it into a DataFrame with the specified column names and data types
for file in file_list:
    df = pd.read_csv(file, compression='gzip', names=column_names, parse_dates=['eventtime'], na_values=['NA'])
    
    # Explicitly convert 'previousitems' column to integer
    #df['previousitems'] = pd.to_numeric(df['previousitems'], errors='coerce', downcast='integer')
    #df['currentscore'] = pd.to_numeric(df['currentscore'], errors='coerce', downcast='float')
    
    df_list.append(df)
    
# Concatenate all DataFrames in the list into a single DataFrame
final_df = pd.concat(df_list, ignore_index=True)

# Now, final_df contains the data from all CSV files

In [88]:
final_df

,studentid,previousitems,itemdifficulty,currentperformance,currentscore,itemid,eventtime,skillid,subskillid
0,26589996,2,0.499486,100,0.656238,3082571b426f,2023-12-05 14:39:42.334,d5a4bfaa479de311b77c005056801da1,ootainee
1,26589996,2,0.228293,100,1.128271,3ad45b088b9e,2023-12-05 14:39:42.339,d5a4bfaa479de311b77c005056801da1,phahnoth
2,26589996,2,-0.680715,0,-0.075620,3bf979d1519a,2023-12-05 14:39:42.344,d5a4bfaa479de311b77c005056801da1,dohweewo
3,40085150,3,-0.105964,100,0.500231,f6166b65e327,2023-12-05 14:39:42.348,72a3bfaa479de311b77c005056801da1,\\N
4,40085150,9,-0.285237,100,0.644498,fd59caa59c3e,2023-12-05 14:39:42.353,70a3bfaa479de311b77c005056801da1,\\N
...,...,...,...,...,...,...,...,...,...
21436056,42007008,2,0.498613,100,1.185687,694f17199345,2023-12-05 15:19:36.053,99a4bfaa479de311b77c005056801da1,\\N
21436057,37284623,2,0.316429,100,1.592607,9301b2dd4532,2023-12-05 15:19:36.057,45a3bfaa479de311b77c005056801da1,\\N
21436058,37284623,3,0.219354,100,1.291225,a5c2abd9a613,2023-12-05 15:19:36.062,45a3bfaa479de311b77c005056801da1,\\N
21436059,37284623,4,0.066582,0,0.611089,9d9d84fc8061,2023-12-05 15:19:36.068,50a3bfaa479de311b77c005056801da1,45a3bfaa479de311b77c005056801da1
21436060,37284623,2,-0.105956,100,0.272940,u8os1i11ldsz,2023-12-05 15:19:36.072,50a3bfaa479de311b77c005056801da1,1db5e33871bd44cda53633af35813c03

In [14]:
!pip install surprise

Collecting surprise
  Downloading surprise-0.1-py2.py3-none-any.whl (1.8 kB)
Collecting scikit-surprise (from surprise)
  Downloading scikit-surprise-1.1.3.tar.gz (771 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.0/772.0 kB 35.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: joblib>=1.0.0 in /home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages (from scikit-surprise->surprise) (1.3.2)
Requirement already satisfied: numpy>=1.17.3 in /home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages (from scikit-surprise->surprise) (1.26.1)
Requirement already satisfied: scipy>=1.3.2 in /home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages (from scikit-surprise->surprise) (1.11.3)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.3-cp310-cp310-linux_x86_64.whl size=1381417 sha256=393e93f9920273eac91023980c1217dc66bb566b8e974b86023dbbfac05d0d3a
  Stored in directory: /home/ec2-user/.cache/pip/wheels/a5/ca/a8/4e28def53797fdc4363ca4af740db15a9c2f1595ebc51fb445
Successfully built scikit-surprise
Installing collected packages: scikit-surprise, surprise
Successfully installed scikit-surprise-1.1.3 surprise-0.1

In [89]:
# Keep only the latest entry for each skillid
latest_scores = final_df.groupby(['studentid', 'skillid']).last().reset_index()
latest_scores

,studentid,skillid,previousitems,itemdifficulty,currentperformance,currentscore,itemid,eventtime,subskillid
0,1707368,37bdc51aa39fe3119503005056801da1,25,0.345682,100,1.118518,49e1e7a433d7,2023-12-06 16:47:30.788,\\N
1,1707368,68a4bfaa479de311b77c005056801da1,7,0.234552,100,0.955899,84ce0de9cdc0,2023-12-06 16:44:09.243,\\N
2,1707368,69a4bfaa479de311b77c005056801da1,5,0.002732,0,1.044169,7a7e065f2878,2023-12-06 16:40:15.724,\\N
3,1707368,6ba4bfaa479de311b77c005056801da1,4,-0.270160,0,0.280686,6981ccfdb38a,2023-12-08 15:07:14.719,\\N
4,1707368,6fa4bfaa479de311b77c005056801da1,20,0.167560,100,0.751880,0f8f953d8988,2023-12-08 15:15:10.461,\\N
...,...,...,...,...,...,...,...,...,...
4064571,47438608,afa4bfaa479de311b77c005056801da1,2,-0.329972,0,-0.129089,3bda9e5856b1,2023-12-19 21:15:40.973,\\N
4064572,47438608,ahvohcoh,2,-0.882960,0,-0.009551,b4fa40b1f060,2023-12-19 21:18:57.633,\\N
4064573,47438608,d0a3bfaa479de311b77c005056801da1,2,-0.318862,100,-0.019928,b761b0973165,2023-12-19 21:28:22.609,\\N
4064574,47438620,99a4bfaa479de311b77c005056801da1,2,0.453962,100,0.992992,8e06887a28a1,2023-12-19 21:27:53.854,\\N
4064575,47438620,9ca4bfaa479de311b77c005056801da1,2,-0.431756,0,0.027495,aab9a440778e,2023-12-19 21:27:53.849,\\N

In [ ]:
from surprise import Dataset, Reader, SVD
import pandas as pd

# Assuming the dataset is in a Pandas DataFrame with columns ['studentid', 'skillid', 'currentscore']
reader = Reader(rating_scale=(0, 1))

# Load the data into a Surprise Dataset
data = Dataset.load_from_df(latest_scores[['studentid', 'skillid', 'currentscore']], reader)


# Assuming data is your Surprise Dataset
unique_user_ids = latest_scores['studentid'].unique()

# Split the user IDs into training and testing sets
split_percentage = 0.8
split_index = int(len(unique_user_ids) * split_percentage)
train_user_ids, test_user_ids  = np.split(unique_user_ids, [split_index])
#train_user_ids, test_user_ids = train_test_split(unique_user_ids, test_size=0.2, random_state=42)

# Construct the training set
trainset = data.build_full_trainset()
trainset_for_test = trainset.build_testset()
trainset_for_test = [elem for elem in trainset_for_test if elem[0] in train_user_ids]

# Use SVD algorithm
algorithm = SVD()

# Train the model
trainset = data.build_full_trainset()
algorithm.fit(trainset)

In [ ]:
# Construct the test set
testset = trainset.build_testset()
testset = [elem for elem in testset if elem[0] in test_user_ids]

# Make predictions on the test set
predictions = algorithm.test(testset)
predictions

In [104]:

# Compute RMSE and MAE for the entire test set
rmse = accuracy.rmse(predictions)
mae = accuracy.mae(predictions)

# Print the results for the entire test set
print(f'RMSE (Entire Test Set): {rmse}')
print(f'MAE (Entire Test Set): {mae}')

RMSE: 0.3126
MAE:  0.2478
RMSE (Entire Test Set): 0.3126105418877624
MAE (Entire Test Set): 0.24781477832924237

In [105]:
# Hold back one skill ID during prediction for evaluation
unique_skill_ids = latest_scores['skillid'].unique()

for held_back_skill_id in unique_skill_ids:
    # Filter predictions and ground truth for the held-back skill ID
    skill_predictions = [pred for pred in predictions if pred[1] == held_back_skill_id]
    skill_ground_truth = [(elem[0], elem[1], elem[2]) for elem in testset if elem[1] == held_back_skill_id]

    # Check if there are predictions and ground truth for the skill ID
    if skill_predictions and skill_ground_truth:
        # Compute RMSE and MAE for the held-back skill ID
        rmse_skill = accuracy.rmse(skill_predictions)
        mae_skill = accuracy.mae(skill_predictions)

        # Print the results for the held-back skill ID
        print(f'\nHeld Back Skill ID: {held_back_skill_id}')
        print(f'RMSE (Held Back Skill ID): {rmse_skill}')
        print(f'MAE (Held Back Skill ID): {mae_skill}')

RMSE: 0.2657
MAE:  0.2093

Held Back Skill ID: 37bdc51aa39fe3119503005056801da1
RMSE (Held Back Skill ID): 0.26568498260896806
MAE (Held Back Skill ID): 0.2093042204632251
RMSE: 0.3369
MAE:  0.2732

Held Back Skill ID: 68a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.336914968265993
MAE (Held Back Skill ID): 0.27319473844277253
RMSE: 0.3474
MAE:  0.2838

Held Back Skill ID: 69a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3474443774086678
MAE (Held Back Skill ID): 0.2838407725348209
RMSE: 0.2716
MAE:  0.2128

Held Back Skill ID: 6ba4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.27161775748256867
MAE (Held Back Skill ID): 0.21275923376050387
RMSE: 0.3271
MAE:  0.2748

Held Back Skill ID: 6fa4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3270800162239255
MAE (Held Back Skill ID): 0.2748082197670019
RMSE: 0.3470
MAE:  0.2892

Held Back Skill ID: 78a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.34701386745754814
MAE (Held Back Skill ID): 0.28915443555368436
RMSE: 0.3387
MAE:  0.2724

Held Back Skill ID: 7db6668c36134063a06b6e23e391f5a5
RMSE (Held Back Skill ID): 0.3387243115235436
MAE (Held Back Skill ID): 0.27243333960968613
RMSE: 0.3697
MAE:  0.3074

Held Back Skill ID: 933af6788dec46fa80ee5af76df721e2
RMSE (Held Back Skill ID): 0.3697286943374682
MAE (Held Back Skill ID): 0.3073977196649697
RMSE: 0.3317
MAE:  0.2678

Held Back Skill ID: cdc25c8447fc4318b9efd56f0f4b0bf2
RMSE (Held Back Skill ID): 0.331718486685866
MAE (Held Back Skill ID): 0.2678423926742389
RMSE: 0.3542
MAE:  0.3032

Held Back Skill ID: iechuquo
RMSE (Held Back Skill ID): 0.3542144901255959
MAE (Held Back Skill ID): 0.3031603892459038
RMSE: 0.3104
MAE:  0.2518

Held Back Skill ID: iefeeyuk
RMSE (Held Back Skill ID): 0.3103694945614904
MAE (Held Back Skill ID): 0.2517535144447464
RMSE: 0.3561
MAE:  0.3037

Held Back Skill ID: paishuji
RMSE (Held Back Skill ID): 0.3561006115855557
MAE (Held Back Skill ID): 0.3036840714594898
RMSE: 0.3261
MAE:  0.2677

Held Back Skill ID: rgrtuhpx
RMSE (Held Back Skill ID): 0.3261326091818023
MAE (Held Back Skill ID): 0.2676722394511732
RMSE: 0.3390
MAE:  0.2943

Held Back Skill ID: yohpecoo
RMSE (Held Back Skill ID): 0.33900590811136877
MAE (Held Back Skill ID): 0.2942903944181218
RMSE: 0.3723
MAE:  0.3055

Held Back Skill ID: 26e9520539ca4695bc50af9fd35578f9
RMSE (Held Back Skill ID): 0.3723034809144844
MAE (Held Back Skill ID): 0.30553843418678456
RMSE: 0.3058
MAE:  0.2542

Held Back Skill ID: 59a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.30580003945920065
MAE (Held Back Skill ID): 0.2541901298532448
RMSE: 0.3434
MAE:  0.3165

Held Back Skill ID: 5adb9ced85844cf0a57b95dc3643d08f
RMSE (Held Back Skill ID): 0.34339603002933805
MAE (Held Back Skill ID): 0.31646776453165903
RMSE: 0.3110
MAE:  0.2591

Held Back Skill ID: 5fa5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3110021861171471
MAE (Held Back Skill ID): 0.2591269612343487
RMSE: 0.2964
MAE:  0.2313

Held Back Skill ID: 84a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.2963746569417618
MAE (Held Back Skill ID): 0.2313254583807727
RMSE: 0.3171
MAE:  0.2419

Held Back Skill ID: 88a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.31714561946528164
MAE (Held Back Skill ID): 0.24188241398108673
RMSE: 0.3841
MAE:  0.3285

Held Back Skill ID: b62ec334aa524c579b8a59f921bb8d65
RMSE (Held Back Skill ID): 0.3841462422834758
MAE (Held Back Skill ID): 0.3284562632103163
RMSE: 0.2547
MAE:  0.1918

Held Back Skill ID: e5535c5ac070419bbf5b20fb0e35b09a
RMSE (Held Back Skill ID): 0.25467811245296756
MAE (Held Back Skill ID): 0.19180821709792722
RMSE: 0.3353
MAE:  0.2702

Held Back Skill ID: yfukezhx
RMSE (Held Back Skill ID): 0.33529163745794155
MAE (Held Back Skill ID): 0.2702006678660019
RMSE: 0.3023
MAE:  0.2543

Held Back Skill ID: 10bdc51aa39fe3119503005056801da1
RMSE (Held Back Skill ID): 0.302304804924933
MAE (Held Back Skill ID): 0.25429908812080393
RMSE: 0.3090
MAE:  0.2341

Held Back Skill ID: 2da4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3090421624630388
MAE (Held Back Skill ID): 0.23411668429050186
RMSE: 0.3284
MAE:  0.2650

Held Back Skill ID: 2ea4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.32843564833089756
MAE (Held Back Skill ID): 0.2649606657194301
RMSE: 0.3187
MAE:  0.2359

Held Back Skill ID: 32a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.31874642591450303
MAE (Held Back Skill ID): 0.23592447258901805
RMSE: 0.3247
MAE:  0.2627

Held Back Skill ID: 34a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.32473863647566703
MAE (Held Back Skill ID): 0.2626592493719502
RMSE: 0.3742
MAE:  0.3205

Held Back Skill ID: 3abbc51aa39fe3119503005056801da1
RMSE (Held Back Skill ID): 0.3741564143751723
MAE (Held Back Skill ID): 0.32049503501151594
RMSE: 0.3291
MAE:  0.2592

Held Back Skill ID: 68379fccdfd54fafb2d79e64b3410156
RMSE (Held Back Skill ID): 0.32908707792421804
MAE (Held Back Skill ID): 0.25916460389268153
RMSE: 0.3110
MAE:  0.2527

Held Back Skill ID: b9a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3109633820599216
MAE (Held Back Skill ID): 0.25272739763538227
RMSE: 0.2904
MAE:  0.2286

Held Back Skill ID: baa3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.2903911195723096
MAE (Held Back Skill ID): 0.22862322288732204
RMSE: 0.3079
MAE:  0.2445

Held Back Skill ID: c3a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.30786665911376887
MAE (Held Back Skill ID): 0.2445264170485407
RMSE: 0.3174
MAE:  0.2604

Held Back Skill ID: nohzooca
RMSE (Held Back Skill ID): 0.31744357108893684
MAE (Held Back Skill ID): 0.2603746062044283
RMSE: 0.3469
MAE:  0.2907

Held Back Skill ID: 74a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.34689778855868103
MAE (Held Back Skill ID): 0.2907449290596644
RMSE: 0.3886
MAE:  0.3160

Held Back Skill ID: 79a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.38862631709259254
MAE (Held Back Skill ID): 0.3159755991305335
RMSE: 0.3953
MAE:  0.3416

Held Back Skill ID: 7aa4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.39525135069926604
MAE (Held Back Skill ID): 0.34163890001398467
RMSE: 0.3015
MAE:  0.2509

Held Back Skill ID: 4656ad7de41f4ca39216d9ccee936597
RMSE (Held Back Skill ID): 0.3015334860665496
MAE (Held Back Skill ID): 0.25094135720091887
RMSE: 0.3540
MAE:  0.2962

Held Back Skill ID: 4ca5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3540142533138571
MAE (Held Back Skill ID): 0.2961853397626606
RMSE: 0.3422
MAE:  0.2860

Held Back Skill ID: 4da5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3422229493602078
MAE (Held Back Skill ID): 0.28595222519373675
RMSE: 0.3313
MAE:  0.2675

Held Back Skill ID: 54a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.33127772942259887
MAE (Held Back Skill ID): 0.2675117891811545
RMSE: 0.2942
MAE:  0.2393

Held Back Skill ID: 5ea5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.2941579437535026
MAE (Held Back Skill ID): 0.2392565533026813
RMSE: 0.3592
MAE:  0.2904

Held Back Skill ID: 86a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3591657266783593
MAE (Held Back Skill ID): 0.2903720859328287
RMSE: 0.3400
MAE:  0.2702

Held Back Skill ID: 8ca5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3399929278530907
MAE (Held Back Skill ID): 0.2702100193575793
RMSE: 0.3559
MAE:  0.2975

Held Back Skill ID: a523a451ac1e491e8b8c91eeeb7f2b8c
RMSE (Held Back Skill ID): 0.35590593377333773
MAE (Held Back Skill ID): 0.29747376655737157
RMSE: 0.2467
MAE:  0.2040

Held Back Skill ID: c85327d309e545d7890d4f18498a76f1
RMSE (Held Back Skill ID): 0.24666486885606512
MAE (Held Back Skill ID): 0.203954114980155
RMSE: 0.3540
MAE:  0.2786

Held Back Skill ID: 4e358085ccf1424086e920b0e1869c3a
RMSE (Held Back Skill ID): 0.3540260724565003
MAE (Held Back Skill ID): 0.2786032003471706
RMSE: 0.2303
MAE:  0.1725

Held Back Skill ID: 7ea4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.23029530653872923
MAE (Held Back Skill ID): 0.17246229809776353
RMSE: 0.3093
MAE:  0.2467

Held Back Skill ID: 80a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.30934975541990384
MAE (Held Back Skill ID): 0.24671446959877827

RMSE: 0.2803
MAE:  0.2316

Held Back Skill ID: 84a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.28028269906681347
MAE (Held Back Skill ID): 0.2315878227124722
RMSE: 0.3215
MAE:  0.2642

Held Back Skill ID: 87a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.321544784919998
MAE (Held Back Skill ID): 0.2641867797586055
RMSE: 0.3070
MAE:  0.2578

Held Back Skill ID: 735f12e14b3d42eb86dc02816aba0cf8
RMSE (Held Back Skill ID): 0.30696893563631306
MAE (Held Back Skill ID): 0.25777349920801773
RMSE: 0.3212
MAE:  0.2532

Held Back Skill ID: 06a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3212208711694891
MAE (Held Back Skill ID): 0.25319494478081583
RMSE: 0.3540
MAE:  0.2829

Held Back Skill ID: 1da5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3539583909766342
MAE (Held Back Skill ID): 0.28288358382375894
RMSE: 0.3375
MAE:  0.2839

Held Back Skill ID: 20a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.33745805820936464
MAE (Held Back Skill ID): 0.2838918005953709
RMSE: 0.3515
MAE:  0.2949

Held Back Skill ID: 25a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3515493059679028
MAE (Held Back Skill ID): 0.2949305733032166
RMSE: 0.3607
MAE:  0.2912

Held Back Skill ID: 4e412280b55e47c8b869591706aa2ea7
RMSE (Held Back Skill ID): 0.3607314368983914
MAE (Held Back Skill ID): 0.2911565882396565
RMSE: 0.2997
MAE:  0.2422

Held Back Skill ID: b773df2a09aa4c51982a9b7806198c28
RMSE (Held Back Skill ID): 0.2997110624687933
MAE (Held Back Skill ID): 0.24215331842013404
RMSE: 0.3693
MAE:  0.3080

Held Back Skill ID: e2a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3693356740235152
MAE (Held Back Skill ID): 0.30802627538139427
RMSE: 0.3561
MAE:  0.3084

Held Back Skill ID: f9a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.35605884058910403
MAE (Held Back Skill ID): 0.3084429257612137
RMSE: 0.3563
MAE:  0.2885

Held Back Skill ID: 58a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3563245799331068
MAE (Held Back Skill ID): 0.2884933858054445
RMSE: 0.3607
MAE:  0.2940

Held Back Skill ID: 5ea4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.36068440989588574
MAE (Held Back Skill ID): 0.2939707352103438
RMSE: 0.3256
MAE:  0.2638

Held Back Skill ID: 63a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3255544220673456
MAE (Held Back Skill ID): 0.2638461233913102
RMSE: 0.3111
MAE:  0.2394

Held Back Skill ID: 66a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3111084810734674
MAE (Held Back Skill ID): 0.23935834776499054
RMSE: 0.2785
MAE:  0.2206

Held Back Skill ID: 8760777bc2a546e7849143971dd69c3c
RMSE (Held Back Skill ID): 0.27845109342348684
MAE (Held Back Skill ID): 0.2205843436444212
RMSE: 0.3806
MAE:  0.3284

Held Back Skill ID: aikaevoy
RMSE (Held Back Skill ID): 0.3806272973217836
MAE (Held Back Skill ID): 0.3283937074480026
RMSE: 0.3381
MAE:  0.2698

Held Back Skill ID: ohthiefo
RMSE (Held Back Skill ID): 0.3381470077621075
MAE (Held Back Skill ID): 0.269834753050114
RMSE: 0.2798
MAE:  0.2159

Held Back Skill ID: afawaexo
RMSE (Held Back Skill ID): 0.27982559873907425
MAE (Held Back Skill ID): 0.21592801310680165
RMSE: 0.2592
MAE:  0.2030

Held Back Skill ID: cfff15088fc648ad9593c77ac6e3e031
RMSE (Held Back Skill ID): 0.25924897406626907
MAE (Held Back Skill ID): 0.20296052507189927
RMSE: 0.2543
MAE:  0.2161

Held Back Skill ID: ffa5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.25428191414865214
MAE (Held Back Skill ID): 0.2161050317670255
RMSE: 0.3105
MAE:  0.2477

Held Back Skill ID: 090e3de89d3f4f9a81e60fb992b655d3
RMSE (Held Back Skill ID): 0.3105356044501537
MAE (Held Back Skill ID): 0.24766043742091287
RMSE: 0.3244
MAE:  0.2624

Held Back Skill ID: 18a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3243513862600258
MAE (Held Back Skill ID): 0.26235227064950745
RMSE: 0.3744
MAE:  0.3082

Held Back Skill ID: 19a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3743712005416989
MAE (Held Back Skill ID): 0.3081580900185982
RMSE: 0.2805
MAE:  0.2159

Held Back Skill ID: 1fbcc51aa39fe3119503005056801da1
RMSE (Held Back Skill ID): 0.2804527366216002
MAE (Held Back Skill ID): 0.2158894574356156
RMSE: 0.2651
MAE:  0.2084

Held Back Skill ID: 38a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.2651058518817427
MAE (Held Back Skill ID): 0.20844253732177573
RMSE: 0.3344
MAE:  0.2700

Held Back Skill ID: 59a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3344497552978424
MAE (Held Back Skill ID): 0.2699573637919315
RMSE: 0.3286
MAE:  0.2626

Held Back Skill ID: 85cec1c3502d4b1fa0b184152a643466
RMSE (Held Back Skill ID): 0.32858973433579336
MAE (Held Back Skill ID): 0.26257275527622564
RMSE: 0.4010
MAE:  0.3510

Held Back Skill ID: 95a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.40102992516386127
MAE (Held Back Skill ID): 0.3510113680264806
RMSE: 0.3992
MAE:  0.3401

Held Back Skill ID: 97a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.399203362927473
MAE (Held Back Skill ID): 0.34006775845430887
RMSE: 0.3372
MAE:  0.2846

Held Back Skill ID: d6a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.33721153368797235
MAE (Held Back Skill ID): 0.2845573723677947
RMSE: 0.2718
MAE:  0.2057

Held Back Skill ID: ee30a13bf08e4880bb4a4ec350837440
RMSE (Held Back Skill ID): 0.2717575968663109
MAE (Held Back Skill ID): 0.20572511575850003
RMSE: 0.3083
MAE:  0.2436

Held Back Skill ID: 8ba5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3083247671003938
MAE (Held Back Skill ID): 0.24356373785522167
RMSE: 0.3375
MAE:  0.2766

Held Back Skill ID: 46a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.33753997163017985
MAE (Held Back Skill ID): 0.2765782382929798
RMSE: 0.3269
MAE:  0.2665

Held Back Skill ID: 49a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.32685273375681123
MAE (Held Back Skill ID): 0.2665266242073284
RMSE: 0.3171
MAE:  0.2520

Held Back Skill ID: be7b5e8e21eae311b64a005056801da1
RMSE (Held Back Skill ID): 0.3170569757583727
MAE (Held Back Skill ID): 0.25196987841345375
RMSE: 0.3399
MAE:  0.2784

Held Back Skill ID: 41a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3399364564300061
MAE (Held Back Skill ID): 0.27837848465440085
RMSE: 0.3844
MAE:  0.3175

Held Back Skill ID: 584d1ed1f674444094abd9f4718a9634
RMSE (Held Back Skill ID): 0.38435408430315837
MAE (Held Back Skill ID): 0.3174875603211304
RMSE: 0.3193
MAE:  0.2644

Held Back Skill ID: 47a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3193099168087776
MAE (Held Back Skill ID): 0.2644494713964095
RMSE: 0.3498
MAE:  0.2818

Held Back Skill ID: 3ea5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.34983148630266964
MAE (Held Back Skill ID): 0.28184114896718704
RMSE: 0.3386
MAE:  0.2851

Held Back Skill ID: 6d2bd40241ea4dafb74370433442f1bd
RMSE (Held Back Skill ID): 0.3386332248307918
MAE (Held Back Skill ID): 0.28508153849447726
RMSE: 0.3406
MAE:  0.2782

Held Back Skill ID: 33a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.34060536781173933
MAE (Held Back Skill ID): 0.2782284534009908
RMSE: 0.3359
MAE:  0.2894

Held Back Skill ID: 39a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.33587220578177024
MAE (Held Back Skill ID): 0.2894356812793008
RMSE: 0.3605
MAE:  0.3035

Held Back Skill ID: 3aa5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.360473452613341
MAE (Held Back Skill ID): 0.30351682563908855
RMSE: 0.3064
MAE:  0.2491

Held Back Skill ID: 3da5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.306405065419138
MAE (Held Back Skill ID): 0.2491026154877565
RMSE: 0.3507
MAE:  0.2781

Held Back Skill ID: 67a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3506649060454046
MAE (Held Back Skill ID): 0.27809659553096366
RMSE: 0.3805
MAE:  0.3197

Held Back Skill ID: 67a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.38051346005377856
MAE (Held Back Skill ID): 0.31969309042155
RMSE: 0.3356
MAE:  0.2757

Held Back Skill ID: 68a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.33564435660682856
MAE (Held Back Skill ID): 0.2757036981140012
RMSE: 0.3033
MAE:  0.2316

Held Back Skill ID: 69a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3032933787934749
MAE (Held Back Skill ID): 0.23164444475459353
RMSE: 0.3362
MAE:  0.2798

Held Back Skill ID: d5a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.33615784978520086
MAE (Held Back Skill ID): 0.27980867367227524

RMSE: 0.3184
MAE:  0.2611

Held Back Skill ID: d7a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.31841913179006265
MAE (Held Back Skill ID): 0.26105281414838705
RMSE: 0.3517
MAE:  0.3001

Held Back Skill ID: dahteeco
RMSE (Held Back Skill ID): 0.35172322824492985
MAE (Held Back Skill ID): 0.3001175914202269
RMSE: 0.3224
MAE:  0.2642

Held Back Skill ID: eca4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.32242960619635674
MAE (Held Back Skill ID): 0.26424163270316875
RMSE: 0.2992
MAE:  0.2408

Held Back Skill ID: kpkxgrti
RMSE (Held Back Skill ID): 0.29920479379009934
MAE (Held Back Skill ID): 0.24080161402012
RMSE: 0.3186
MAE:  0.2527

Held Back Skill ID: 341bf9aee38846df9c59842a7b460015
RMSE (Held Back Skill ID): 0.3186312038224271
MAE (Held Back Skill ID): 0.25270358985667946
RMSE: 0.3231
MAE:  0.2664

Held Back Skill ID: 44a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3231130322191411
MAE (Held Back Skill ID): 0.2663569134581475
RMSE: 0.2135
MAE:  0.1569

Held Back Skill ID: 01a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.21348439222736046
MAE (Held Back Skill ID): 0.15687605753452505
RMSE: 0.1475
MAE:  0.0863

Held Back Skill ID: 02a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.14746428998366282
MAE (Held Back Skill ID): 0.08631387641976497
RMSE: 0.3137
MAE:  0.2515

Held Back Skill ID: fea2bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3136747300696841
MAE (Held Back Skill ID): 0.25147005805017625
RMSE: 0.3697
MAE:  0.3094

Held Back Skill ID: 56a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.36967994936966564
MAE (Held Back Skill ID): 0.30940554932816144
RMSE: 0.3354
MAE:  0.2745

Held Back Skill ID: 71acbbfabd284348b0ac319aff6e0578
RMSE (Held Back Skill ID): 0.3354470055641883
MAE (Held Back Skill ID): 0.2745438178137644
RMSE: 0.2751
MAE:  0.2107

Held Back Skill ID: 9fa3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.2750811387538117
MAE (Held Back Skill ID): 0.2106522934290327
RMSE: 0.2420
MAE:  0.1837

Held Back Skill ID: a0a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.24197079799411836
MAE (Held Back Skill ID): 0.18371395084286146
RMSE: 0.3218
MAE:  0.2616

Held Back Skill ID: a4a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.32184085256069933
MAE (Held Back Skill ID): 0.2616258632248888
RMSE: 0.3595
MAE:  0.2933

Held Back Skill ID: a6a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.35954412843578387
MAE (Held Back Skill ID): 0.2932531145742029
RMSE: 0.3410
MAE:  0.2819

Held Back Skill ID: dda3108b5fbf4c28afd1fec18e021e7a
RMSE (Held Back Skill ID): 0.3410337852149002
MAE (Held Back Skill ID): 0.2818660205205958
RMSE: 0.3350
MAE:  0.2779

Held Back Skill ID: 6d8c3026c1674eff8375d7684e7e0069
RMSE (Held Back Skill ID): 0.33498663196630735
MAE (Held Back Skill ID): 0.2778649025146725
RMSE: 0.3271
MAE:  0.2644

Held Back Skill ID: 8da5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3270823659045256
MAE (Held Back Skill ID): 0.2644107547987944
RMSE: 0.3245
MAE:  0.2615

Held Back Skill ID: e9a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3244983383672298
MAE (Held Back Skill ID): 0.2614814065207575
RMSE: 0.3734
MAE:  0.3096

Held Back Skill ID: eba3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.373442520012683
MAE (Held Back Skill ID): 0.3095814080932474
RMSE: 0.3085
MAE:  0.2397

Held Back Skill ID: 9fa4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3084777203526089
MAE (Held Back Skill ID): 0.23971940426697977
RMSE: 0.3412
MAE:  0.2912

Held Back Skill ID: a2a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.34124938840864516
MAE (Held Back Skill ID): 0.29118201391188075
RMSE: 0.3299
MAE:  0.2691

Held Back Skill ID: a3a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.32986212088369354
MAE (Held Back Skill ID): 0.2690784606054218
RMSE: 0.2805
MAE:  0.2209

Held Back Skill ID: bctpfgts
RMSE (Held Back Skill ID): 0.28048750323795646
MAE (Held Back Skill ID): 0.22089352181224442
RMSE: 0.3133
MAE:  0.2496

Held Back Skill ID: d88c7277923544919f499645ff509bd6
RMSE (Held Back Skill ID): 0.3133490947512285
MAE (Held Back Skill ID): 0.24959712287448355
RMSE: 0.2903
MAE:  0.2253

Held Back Skill ID: 297dcdf7d5014527906b62565e3c9107
RMSE (Held Back Skill ID): 0.2902504249865812
MAE (Held Back Skill ID): 0.22527345829505913
RMSE: 0.2779
MAE:  0.2140

Held Back Skill ID: 3ea4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.27791062591984517
MAE (Held Back Skill ID): 0.2140368383195864
RMSE: 0.2820
MAE:  0.2259

Held Back Skill ID: 40a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.2819816942126837
MAE (Held Back Skill ID): 0.2259363456603904
RMSE: 0.2848
MAE:  0.2247

Held Back Skill ID: 41a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.28479417558099873
MAE (Held Back Skill ID): 0.22471165950943356
RMSE: 0.2703
MAE:  0.2108

Held Back Skill ID: 43a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.2703345828307614
MAE (Held Back Skill ID): 0.21082778784247883
RMSE: 0.3398
MAE:  0.2747

Held Back Skill ID: 45a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.33975579826872215
MAE (Held Back Skill ID): 0.2747273435102022
RMSE: 0.2733
MAE:  0.2146

Held Back Skill ID: 45a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.27328732609647416
MAE (Held Back Skill ID): 0.21459659582570004
RMSE: 0.2178
MAE:  0.1557

Held Back Skill ID: 49a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.21779124165567887
MAE (Held Back Skill ID): 0.15572499572899873
RMSE: 0.2686
MAE:  0.1939

Held Back Skill ID: 4ca4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.2685690430865509
MAE (Held Back Skill ID): 0.19389162761386722
RMSE: 0.2918
MAE:  0.2358

Held Back Skill ID: 4da4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.29183597018919893
MAE (Held Back Skill ID): 0.23580639304972686
RMSE: 0.3652
MAE:  0.3016

Held Back Skill ID: 604ca9d8298b4fa68d5e3c8e68af7cc2
RMSE (Held Back Skill ID): 0.36521962712669953
MAE (Held Back Skill ID): 0.30159338201631175
RMSE: 0.3296
MAE:  0.2666

Held Back Skill ID: 8e30d138f63c4545884966ef4c650f16
RMSE (Held Back Skill ID): 0.3296168249688952
MAE (Held Back Skill ID): 0.2665642823957271
RMSE: 0.3976
MAE:  0.3335

Held Back Skill ID: 94d01b8e094b46b19ec8adc8e14bc887
RMSE (Held Back Skill ID): 0.3975745216470067
MAE (Held Back Skill ID): 0.33350663485397697
RMSE: 0.3057
MAE:  0.2463

Held Back Skill ID: 94dae4aa0077458e8f01fbe1bace042b
RMSE (Held Back Skill ID): 0.30566576703108045
MAE (Held Back Skill ID): 0.24628225326461145
RMSE: 0.3769
MAE:  0.3099

Held Back Skill ID: eaa3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3769057403667573
MAE (Held Back Skill ID): 0.30992032447659584
RMSE: 0.3570
MAE:  0.2961

Held Back Skill ID: efa3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.35699858221561753
MAE (Held Back Skill ID): 0.2960698223689234
RMSE: 0.3211
MAE:  0.2608

Held Back Skill ID: xafohsha
RMSE (Held Back Skill ID): 0.3210912736187226
MAE (Held Back Skill ID): 0.26084109446911585
RMSE: 0.3225
MAE:  0.2577

Held Back Skill ID: aba3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.32254085214327394
MAE (Held Back Skill ID): 0.25767802519267285
RMSE: 0.3557
MAE:  0.3081

Held Back Skill ID: b3a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.35574289324208397
MAE (Held Back Skill ID): 0.3080717827869064
RMSE: 0.2105
MAE:  0.1497

Held Back Skill ID: 99bcc51aa39fe3119503005056801da1
RMSE (Held Back Skill ID): 0.2104616033726515
MAE (Held Back Skill ID): 0.14969625764992506
RMSE: 0.2819
MAE:  0.2231

Held Back Skill ID: dea3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.2818654246816075
MAE (Held Back Skill ID): 0.22311072440028154
RMSE: 0.3043
MAE:  0.2508

Held Back Skill ID: 56a5bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.304325907618832
MAE (Held Back Skill ID): 0.2507856501269176
RMSE: 0.2949
MAE:  0.2278

Held Back Skill ID: 39a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.29493506495653465
MAE (Held Back Skill ID): 0.22775271180554538
RMSE: 0.3358
MAE:  0.2751

Held Back Skill ID: 9ba4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3358451606388858
MAE (Held Back Skill ID): 0.2750512918435687
RMSE: 0.3284
MAE:  0.2722

Held Back Skill ID: d8a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.328413140863656
MAE (Held Back Skill ID): 0.2721888601707364

RMSE: 0.3556
MAE:  0.2854

Held Back Skill ID: d9a3bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.35561214742564523
MAE (Held Back Skill ID): 0.28536317484831186
RMSE: 0.3302
MAE:  0.2568

Held Back Skill ID: 02a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.33021625048217773
MAE (Held Back Skill ID): 0.2567904012425813
RMSE: 0.2968
MAE:  0.2370

Held Back Skill ID: 03a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.2968024281505736
MAE (Held Back Skill ID): 0.2369856000942157
RMSE: 0.3280
MAE:  0.2703

Held Back Skill ID: 05a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3279906631145399
MAE (Held Back Skill ID): 0.27034050738573173
RMSE: 0.3533
MAE:  0.3006

Held Back Skill ID: 07a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.35329337531600635
MAE (Held Back Skill ID): 0.3006228905568536
RMSE: 0.2579
MAE:  0.2023

Held Back Skill ID: 0da4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.25794855311994186
MAE (Held Back Skill ID): 0.2023102059242793
RMSE: 0.2956
MAE:  0.2344

Held Back Skill ID: 0ea4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.2956303882256868
MAE (Held Back Skill ID): 0.23440345378424768
RMSE: 0.3076
MAE:  0.2473

Held Back Skill ID: 10a4bfaa479de311b77c005056801da1
RMSE (Held Back Skill ID): 0.3075763830027913
MAE (Held Back Skill ID): 0.24730682077510283

KeyboardInterrupt:

In [106]:
held_back_skill_id

'11a4bfaa479de311b77c005056801da1'

In [116]:
#fake test user

#predictions = algorithm.test(testset)

faketest = [(999999999,'eda4bfaa479de311b77c005056801da1',1),
            (999999999,'3ea5bfaa479de311b77c005056801da1',1),
            (999999999,'5fa5bfaa479de311b77c005056801da1',1)]

new_user_skills=[]
for row in faketest:
    new_user_skills.append(row[1])
    
print(new_user_skills)

new_user_predictions = []
for skill_id in unique_skill_ids:
    if skill_id not in new_user_skills:
        # Make a prediction for each unseen skill
        prediction = algorithm.predict('new_user', skill_id)
        new_user_predictions.append(prediction)

for prediction in new_user_predictions:
    print(f"User ID: {prediction.uid}, Skill ID: {prediction.iid}, True Rating: {prediction.r_ui}, Estimated Rating: {prediction.est}")

['eda4bfaa479de311b77c005056801da1', '3ea5bfaa479de311b77c005056801da1', '5fa5bfaa479de311b77c005056801da1']
User ID: new_user, Skill ID: 37bdc51aa39fe3119503005056801da1, True Rating: None, Estimated Rating: 0.7037768839488503
User ID: new_user, Skill ID: 68a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6605679794474429
User ID: new_user, Skill ID: 69a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5249970936306955
User ID: new_user, Skill ID: 6ba4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.35608884937839397
User ID: new_user, Skill ID: 6fa4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5362811115012548
User ID: new_user, Skill ID: 78a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4739445256592183
User ID: new_user, Skill ID: 7db6668c36134063a06b6e23e391f5a5, True Rating: None, Estimated Rating: 0.5422012272960044
User ID: new_user, Skill ID: 933af6788dec46fa80ee5af76df721e2, True Rating: None, Estimated Rating: 0.5118795009800435
User ID: new_user, Skill ID: cdc25c8447fc4318b9efd56f0f4b0bf2, True Rating: None, Estimated Rating: 0.492345963482026
User ID: new_user, Skill ID: iechuquo, True Rating: None, Estimated Rating: 0.539603471420461
User ID: new_user, Skill ID: iefeeyuk, True Rating: None, Estimated Rating: 0.2163397399035673
User ID: new_user, Skill ID: paishuji, True Rating: None, Estimated Rating: 0.6104663934894303
User ID: new_user, Skill ID: rgrtuhpx, True Rating: None, Estimated Rating: 0.3878327125425122
User ID: new_user, Skill ID: yohpecoo, True Rating: None, Estimated Rating: 0.6019318659649227
User ID: new_user, Skill ID: 26e9520539ca4695bc50af9fd35578f9, True Rating: None, Estimated Rating: 0.4629207889152268
User ID: new_user, Skill ID: 59a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.3709640362394765
User ID: new_user, Skill ID: 5adb9ced85844cf0a57b95dc3643d08f, True Rating: None, Estimated Rating: 0.35514621143465236
User ID: new_user, Skill ID: 84a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6437182755795239
User ID: new_user, Skill ID: 88a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.21572933476047212
User ID: new_user, Skill ID: b62ec334aa524c579b8a59f921bb8d65, True Rating: None, Estimated Rating: 0.3756087948697737
User ID: new_user, Skill ID: e5535c5ac070419bbf5b20fb0e35b09a, True Rating: None, Estimated Rating: 0.7491274478277548
User ID: new_user, Skill ID: yfukezhx, True Rating: None, Estimated Rating: 0.6055436319208307
User ID: new_user, Skill ID: 10bdc51aa39fe3119503005056801da1, True Rating: None, Estimated Rating: 0.5459391571331544
User ID: new_user, Skill ID: 2da4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7947139279775038
User ID: new_user, Skill ID: 2ea4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.691919133454805
User ID: new_user, Skill ID: 32a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.8041978236556263
User ID: new_user, Skill ID: 34a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.49259075205459035
User ID: new_user, Skill ID: 3abbc51aa39fe3119503005056801da1, True Rating: None, Estimated Rating: 0.5151518792305847
User ID: new_user, Skill ID: 68379fccdfd54fafb2d79e64b3410156, True Rating: None, Estimated Rating: 0.5302344781562018
User ID: new_user, Skill ID: b9a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.64463556528648
User ID: new_user, Skill ID: baa3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6795061990480673
User ID: new_user, Skill ID: c3a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.8114055423017467
User ID: new_user, Skill ID: nohzooca, True Rating: None, Estimated Rating: 0.48628376501917653
User ID: new_user, Skill ID: 74a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.33973748990803304
User ID: new_user, Skill ID: 79a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6394110477229009
User ID: new_user, Skill ID: 7aa4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4167981126284246
User ID: new_user, Skill ID: 4656ad7de41f4ca39216d9ccee936597, True Rating: None, Estimated Rating: 0.29995282154964725
User ID: new_user, Skill ID: 4ca5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4758843256273915
User ID: new_user, Skill ID: 4da5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5912495804454675
User ID: new_user, Skill ID: 54a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6244761069065992
User ID: new_user, Skill ID: 5ea5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.39832756132867886
User ID: new_user, Skill ID: 86a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.3640868408246075
User ID: new_user, Skill ID: 8ca5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.552821250833444
User ID: new_user, Skill ID: a523a451ac1e491e8b8c91eeeb7f2b8c, True Rating: None, Estimated Rating: 0.4035132139739422
User ID: new_user, Skill ID: c85327d309e545d7890d4f18498a76f1, True Rating: None, Estimated Rating: 0.6275436126147396
User ID: new_user, Skill ID: 4e358085ccf1424086e920b0e1869c3a, True Rating: None, Estimated Rating: 0.4455171629461195
User ID: new_user, Skill ID: 7ea4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5541034888370691
User ID: new_user, Skill ID: 80a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4724001739710084
User ID: new_user, Skill ID: 84a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6372887382294942
User ID: new_user, Skill ID: 87a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4834245404877517
User ID: new_user, Skill ID: 735f12e14b3d42eb86dc02816aba0cf8, True Rating: None, Estimated Rating: 0.48379944332495306
User ID: new_user, Skill ID: 06a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6441740797836331
User ID: new_user, Skill ID: 1da5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4703358825049555
User ID: new_user, Skill ID: 20a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4325752170768582
User ID: new_user, Skill ID: 25a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5658804129270387
User ID: new_user, Skill ID: 4e412280b55e47c8b869591706aa2ea7, True Rating: None, Estimated Rating: 0.6402276202884934
User ID: new_user, Skill ID: b773df2a09aa4c51982a9b7806198c28, True Rating: None, Estimated Rating: 0.6404102294391754
User ID: new_user, Skill ID: e2a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5016046060945688
User ID: new_user, Skill ID: f9a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5579148257003413
User ID: new_user, Skill ID: 58a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.568111053445098
User ID: new_user, Skill ID: 5ea4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5657213342229839
User ID: new_user, Skill ID: 63a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6654981470106608
User ID: new_user, Skill ID: 66a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7222880377305634
User ID: new_user, Skill ID: 8760777bc2a546e7849143971dd69c3c, True Rating: None, Estimated Rating: 0.7027583722810496
User ID: new_user, Skill ID: aikaevoy, True Rating: None, Estimated Rating: 0.419903743752696
User ID: new_user, Skill ID: ohthiefo, True Rating: None, Estimated Rating: 0.626380072909223
User ID: new_user, Skill ID: afawaexo, True Rating: None, Estimated Rating: 0.4967890894202426
User ID: new_user, Skill ID: cfff15088fc648ad9593c77ac6e3e031, True Rating: None, Estimated Rating: 0.409873098322399
User ID: new_user, Skill ID: ffa5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4481503751818301
User ID: new_user, Skill ID: 090e3de89d3f4f9a81e60fb992b655d3, True Rating: None, Estimated Rating: 0.7029857672604816
User ID: new_user, Skill ID: 18a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5048622545456527
User ID: new_user, Skill ID: 19a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5064489414305933
User ID: new_user, Skill ID: 1fbcc51aa39fe3119503005056801da1, True Rating: None, Estimated Rating: 0.7753486305296877
User ID: new_user, Skill ID: 38a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7519301376307819
User ID: new_user, Skill ID: 59a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.47573005228807586
User ID: new_user, Skill ID: 85cec1c3502d4b1fa0b184152a643466, True Rating: None, Estimated Rating: 0.5817662783548858
User ID: new_user, Skill ID: 95a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4861416899303642
User ID: new_user, Skill ID: 97a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6460267024118821
User ID: new_user, Skill ID: d6a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.42162985341914005
User ID: new_user, Skill ID: ee30a13bf08e4880bb4a4ec350837440, True Rating: None, Estimated Rating: 0.8040632066102534
User ID: new_user, Skill ID: 8ba5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5996340963685749
User ID: new_user, Skill ID: 46a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.49873365829032057
User ID: new_user, Skill ID: 49a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.42684681783645373
User ID: new_user, Skill ID: be7b5e8e21eae311b64a005056801da1, True Rating: None, Estimated Rating: 0.6472341707725464
User ID: new_user, Skill ID: 41a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5479891846973401
User ID: new_user, Skill ID: 584d1ed1f674444094abd9f4718a9634, True Rating: None, Estimated Rating: 0.5598901184534835
User ID: new_user, Skill ID: 47a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.617716884499147
User ID: new_user, Skill ID: 6d2bd40241ea4dafb74370433442f1bd, True Rating: None, Estimated Rating: 0.6700467494684272
User ID: new_user, Skill ID: 33a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7230103069677373
User ID: new_user, Skill ID: 39a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4439393758421778
User ID: new_user, Skill ID: 3aa5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4991409360002442
User ID: new_user, Skill ID: 3da5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5845506151924842
User ID: new_user, Skill ID: 67a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7022007351103587
User ID: new_user, Skill ID: 67a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4610832393195574
User ID: new_user, Skill ID: 68a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.37797370155117743
User ID: new_user, Skill ID: 69a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.1759825924055513
User ID: new_user, Skill ID: d5a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.39753934832159094
User ID: new_user, Skill ID: d7a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6555756749505883
User ID: new_user, Skill ID: dahteeco, True Rating: None, Estimated Rating: 0.3572046617604613
User ID: new_user, Skill ID: eca4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6060943476172452
User ID: new_user, Skill ID: kpkxgrti, True Rating: None, Estimated Rating: 0.2583624214553419
User ID: new_user, Skill ID: 341bf9aee38846df9c59842a7b460015, True Rating: None, Estimated Rating: 0.6801569922336531
User ID: new_user, Skill ID: 44a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5985924347277056
User ID: new_user, Skill ID: 01a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.8840958583669423
User ID: new_user, Skill ID: 02a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.9286671160060418
User ID: new_user, Skill ID: fea2bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7321789692554693
User ID: new_user, Skill ID: 56a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5976393321810125
User ID: new_user, Skill ID: 71acbbfabd284348b0ac319aff6e0578, True Rating: None, Estimated Rating: 0.5027367039920293
User ID: new_user, Skill ID: 9fa3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.793414554965023
User ID: new_user, Skill ID: a0a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.8230561652658304
User ID: new_user, Skill ID: a4a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6134897621332775
User ID: new_user, Skill ID: a6a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6039325026488673
User ID: new_user, Skill ID: dda3108b5fbf4c28afd1fec18e021e7a, True Rating: None, Estimated Rating: 0.526194862743233
User ID: new_user, Skill ID: 6d8c3026c1674eff8375d7684e7e0069, True Rating: None, Estimated Rating: 0.5054199335814676
User ID: new_user, Skill ID: 8da5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7357233947416568
User ID: new_user, Skill ID: e9a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5286140310198797
User ID: new_user, Skill ID: eba3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5106111320265119
User ID: new_user, Skill ID: 9fa4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7229302756309888
User ID: new_user, Skill ID: a2a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5335438443588426
User ID: new_user, Skill ID: a3a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.60537615164841
User ID: new_user, Skill ID: bctpfgts, True Rating: None, Estimated Rating: 0.7761855259600924
User ID: new_user, Skill ID: d88c7277923544919f499645ff509bd6, True Rating: None, Estimated Rating: 0.6744981293648012
User ID: new_user, Skill ID: 297dcdf7d5014527906b62565e3c9107, True Rating: None, Estimated Rating: 0.8118450376989561
User ID: new_user, Skill ID: 3ea4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7783003708284809
User ID: new_user, Skill ID: 40a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7229613338197234
User ID: new_user, Skill ID: 41a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7437889279272194
User ID: new_user, Skill ID: 43a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7766157647865265
User ID: new_user, Skill ID: 45a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5286585194745734
User ID: new_user, Skill ID: 45a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7539778941280089
User ID: new_user, Skill ID: 49a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.8569090512047257
User ID: new_user, Skill ID: 4ca4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.8337359213838431
User ID: new_user, Skill ID: 4da4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7733465395063489
User ID: new_user, Skill ID: 604ca9d8298b4fa68d5e3c8e68af7cc2, True Rating: None, Estimated Rating: 0.48825643131483637
User ID: new_user, Skill ID: 8e30d138f63c4545884966ef4c650f16, True Rating: None, Estimated Rating: 0.6726980255840097
User ID: new_user, Skill ID: 94d01b8e094b46b19ec8adc8e14bc887, True Rating: None, Estimated Rating: 0.34157074561072925
User ID: new_user, Skill ID: 94dae4aa0077458e8f01fbe1bace042b, True Rating: None, Estimated Rating: 0.6901794569554885
User ID: new_user, Skill ID: eaa3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5079407085955214
User ID: new_user, Skill ID: efa3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5993078909176287
User ID: new_user, Skill ID: xafohsha, True Rating: None, Estimated Rating: 0.6472756310632385
User ID: new_user, Skill ID: aba3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6505945709779686
User ID: new_user, Skill ID: b3a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4867055261679383
User ID: new_user, Skill ID: 99bcc51aa39fe3119503005056801da1, True Rating: None, Estimated Rating: 0.876225022353778
User ID: new_user, Skill ID: dea3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7322988628213717
User ID: new_user, Skill ID: 56a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.4105998129780025
User ID: new_user, Skill ID: 39a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7598702278401666
User ID: new_user, Skill ID: 9ba4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5487029547206923
User ID: new_user, Skill ID: d8a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5787956920073741
User ID: new_user, Skill ID: d9a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6275513703313659
User ID: new_user, Skill ID: 02a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5776361381628832
User ID: new_user, Skill ID: 03a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.699134013666919
User ID: new_user, Skill ID: 05a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5927636394237822
User ID: new_user, Skill ID: 07a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.43420178551114236
User ID: new_user, Skill ID: 0da4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7517564270170143
User ID: new_user, Skill ID: 0ea4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.608410010245192
User ID: new_user, Skill ID: 10a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.7101417658027738
User ID: new_user, Skill ID: 11a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6678021807261239
User ID: new_user, Skill ID: 14a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6357567494508709
User ID: new_user, Skill ID: 28a5bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.289848766190854
User ID: new_user, Skill ID: 34310c9f27264a42bcd583551d78aee9, True Rating: None, Estimated Rating: 0.6563523314518551
User ID: new_user, Skill ID: 8e8fa04ea6da4780a6ffe24cfc1f56ea, True Rating: None, Estimated Rating: 0.5907126495470418
User ID: new_user, Skill ID: 95bcc51aa39fe3119503005056801da1, True Rating: None, Estimated Rating: 0.6471119377707771
User ID: new_user, Skill ID: 98e65c575b224d45848cb42b6aa7f2ac, True Rating: None, Estimated Rating: 0.2700032032627926
User ID: new_user, Skill ID: 9cc61e8eb0d24540a43ca6bf40cd25ec, True Rating: None, Estimated Rating: 0.7480017628898336
User ID: new_user, Skill ID: b975030e84c74d96a51d4df1fad93ff5, True Rating: None, Estimated Rating: 0.6095262188051646
User ID: new_user, Skill ID: baengiex, True Rating: None, Estimated Rating: 0.5460829975342828
User ID: new_user, Skill ID: e3a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.43682724862752464
User ID: new_user, Skill ID: e5a4bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.6402338416154397
User ID: new_user, Skill ID: edatcmao, True Rating: None, Estimated Rating: 0.6043956677201978
User ID: new_user, Skill ID: f3bbc51aa39fe3119503005056801da1, True Rating: None, Estimated Rating: 0.6262649237145197
User ID: new_user, Skill ID: f5a3bfaa479de311b77c005056801da1, True Rating: None, Estimated Rating: 0.5690998465533621

In [ ]:
# Now, let's evaluate by dropping one skill_id score at a time for each user
# Accumulate true scores and predictions for each modification
true_scores = []
modified_predictions = []

#get all user ids in testset
unique_user_ids = list(set([elem[0] for elem in testset]))

# Iterate over each user in the test set
for user_id in unique_user_ids: 
    user_testset = [elem for elem in testset if elem[0] == user_id]

    for true_skill_id, true_score, _ in user_testset:
        # Copy the user test set and remove the true skill_id score
        modified_testset = [elem for elem in user_testset if elem[1] != true_skill_id]

        # Make a prediction for the modified test set
        modified_prediction = algorithm.predict(user_id, true_skill_id)

        # Accumulate true scores and predictions
        true_scores.append(true_score)
        modified_predictions.append(modified_prediction.est)

# Compute RMSE and MAE for all dropout predictions
rmse_dropout = accuracy.rmse([(true, pred) for true, pred in zip(true_scores, modified_predictions)])
mae_dropout = accuracy.mae([(true, pred) for true, pred in zip(true_scores, modified_predictions)])

print(f'RMSE on Dropout Predictions: {rmse_dropout}')
print(f'MAE on Dropout Predictions: {mae_dropout}')

In [ ]:
rmse_dropout = accuracy.rmse([(true, pred) for true, pred in zip(true_scores, modified_predictions)])
mae_dropout = accuracy.mae([(true, pred) for true, pred in zip(true_scores, modified_predictions)])

print(f'RMSE on Dropout Predictions: {rmse_dropout}')
print(f'MAE on Dropout Predictions: {mae_dropout}')

In [17]:
accuracy.rmse(predictions)

RMSE: 0.2951

0.2950919756397519

In [52]:

# Specify the user for whom you want to impute ratings for all other skills
user_id = 44221404

# Get all skills (items) that the user has not rated
all_skills = final_df['skillid'].unique()
rated_skills = final_df[final_df['studentid'] == user_id]['skillid'].unique()
unrated_skills = set(all_skills) - set(rated_skills)

# Generate predictions for unrated skills
imputed_ratings = [(user_id, item_id, algorithm.predict(user_id, item_id).est) for item_id in unrated_skills]

# Print the imputed ratings
for user_id, item_id, imputed_rating in imputed_ratings:
    print(f"User {user_id} - Skill {item_id}: Imputed Rating = {imputed_rating}")

User 44221404 - Skill 9f04bd21acc34c6f849324d339c84422: Imputed Rating = 0.859542726720917
User 44221404 - Skill 697e63d82400e4119e54005056801da1: Imputed Rating = 0.6166621736229205
User 44221404 - Skill a6a3bfaa479de311b77c005056801da1: Imputed Rating = 0.6670623806561423
User 44221404 - Skill 27a3bfaa479de311b77c005056801da1: Imputed Rating = 0.5963353047297132
User 44221404 - Skill 31bec51aa39fe3119503005056801da1: Imputed Rating = 0.629265221579426
User 44221404 - Skill 28a6bfaa479de311b77c005056801da1: Imputed Rating = 0.5347882231166186
User 44221404 - Skill ooghahte: Imputed Rating = 0.7395411951665554
User 44221404 - Skill 6ba4bfaa479de311b77c005056801da1: Imputed Rating = 0.4939535673430723
User 44221404 - Skill ada3bfaa479de311b77c005056801da1: Imputed Rating = 0.778126050064583
User 44221404 - Skill bdba0954428c45f99ac6c3f437c645e6: Imputed Rating = 0.8383085107994892
User 44221404 - Skill wifieyei: Imputed Rating = 0.8015341950737063
User 44221404 - Skill d5a4bfaa479de311b77c005056801da1: Imputed Rating = 0.4774710935949473
User 44221404 - Skill 418063d82400e4119e54005056801da1: Imputed Rating = 0.7293079127583506
User 44221404 - Skill 8fbac51aa39fe3119503005056801da1: Imputed Rating = 0.7588350765981363
User 44221404 - Skill 9aeb4102103740c39e037ad4d3f94ce1: Imputed Rating = 0.6814068283007654
User 44221404 - Skill iegohmor: Imputed Rating = 0.500463779099038
User 44221404 - Skill e225d89e2b8e4d16909e2e5eb8392a9d: Imputed Rating = 0.5557564735749085
User 44221404 - Skill tbupfjma: Imputed Rating = 0.45066420732396395
User 44221404 - Skill 9aa6bfaa479de311b77c005056801da1: Imputed Rating = 0.23231185395897838
User 44221404 - Skill 8ca3bfaa479de311b77c005056801da1: Imputed Rating = 0.5756286729297498
User 44221404 - Skill efbdc51aa39fe3119503005056801da1: Imputed Rating = 0.8619964602134533
User 44221404 - Skill 957e63d82400e4119e54005056801da1: Imputed Rating = 0.6072273682529266
User 44221404 - Skill 341bf9aee38846df9c59842a7b460015: Imputed Rating = 0.6931304488844587
User 44221404 - Skill 783ce241035a4f03952f3c5d7d994c15: Imputed Rating = 0.48933510390212115
User 44221404 - Skill 56c13db64f7746bbad0fe35092c4ad81: Imputed Rating = 0.8376673837428562
User 44221404 - Skill fdfa71fe582d40b784f2e46835a2502e: Imputed Rating = 0.5741627023205251
User 44221404 - Skill 50a3bfaa479de311b77c005056801da1: Imputed Rating = 0.5726515778039324
User 44221404 - Skill 1f25d70975324768829fd0f935f66295: Imputed Rating = 0.35341226743677157
User 44221404 - Skill 361822364d68442e982380cd2ce94a89: Imputed Rating = 0.8924354028424012
User 44221404 - Skill 998063d82400e4119e54005056801da1: Imputed Rating = 0.7176682143785866
User 44221404 - Skill 0993a8da10e44884a53462ab2e2b2d58: Imputed Rating = 0.635397625342547
User 44221404 - Skill bba3bfaa479de311b77c005056801da1: Imputed Rating = 0.7073106338761448
User 44221404 - Skill 32a3bfaa479de311b77c005056801da1: Imputed Rating = 0.8963839466374662
User 44221404 - Skill ungiecoo: Imputed Rating = 0.7699864026743815
User 44221404 - Skill 9c5490f2e2da4154a6eeea25b453b248: Imputed Rating = 0.7659337851240501
User 44221404 - Skill e0d131a0a1cb41198ae0519bc4c82ff4: Imputed Rating = 0.7745041824075021
User 44221404 - Skill 717f63d82400e4119e54005056801da1: Imputed Rating = 0.5412622822642701
User 44221404 - Skill e05419e6a61b4e54af66c58a3d4e5e8f: Imputed Rating = 0.8419323587393562
User 44221404 - Skill 99bcc51aa39fe3119503005056801da1: Imputed Rating = 0.9717203063641268
User 44221404 - Skill c16f6064e5d2440791a89517a8b6de9c: Imputed Rating = 0.7754358801099284
User 44221404 - Skill 23bcc51aa39fe3119503005056801da1: Imputed Rating = 0.6299959653616535
User 44221404 - Skill b1bac51aa39fe3119503005056801da1: Imputed Rating = 1
User 44221404 - Skill f93d8c9076bf4301aa3cb7c5603c3947: Imputed Rating = 0.5709068353817368
User 44221404 - Skill 71a5bfaa479de311b77c005056801da1: Imputed Rating = 0.8333238696456626
User 44221404 - Skill 9fa6bfaa479de311b77c005056801da1: Imputed Rating = 0.5426160808389127
User 44221404 - Skill jdxvtywq: Imputed Rating = 0.6336138623485176
User 44221404 - Skill quoonoof: Imputed Rating = 0.5694721315124057
User 44221404 - Skill 96bdc51aa39fe3119503005056801da1: Imputed Rating = 0.7344047068199302
User 44221404 - Skill f07d64c2b66f43b4baf0f9189d08546a: Imputed Rating = 0.5462810494439836
User 44221404 - Skill e18063d82400e4119e54005056801da1: Imputed Rating = 0.6865917295280887
User 44221404 - Skill 02a3bfaa479de311b77c005056801da1: Imputed Rating = 0.999507487240971
User 44221404 - Skill 897f63d82400e4119e54005056801da1: Imputed Rating = 0.5248196848334781
User 44221404 - Skill 43a5bfaa479de311b77c005056801da1: Imputed Rating = 0.5173769949440442
User 44221404 - Skill 33292fe282c2472ebc335b860eb8518e: Imputed Rating = 0.7148688031157632
User 44221404 - Skill 8760777bc2a546e7849143971dd69c3c: Imputed Rating = 0.7715748065311444
User 44221404 - Skill yaiphowo: Imputed Rating = 0.6470623644874639
User 44221404 - Skill 2fbec51aa39fe3119503005056801da1: Imputed Rating = 0.46421736024764776
User 44221404 - Skill 33bcc51aa39fe3119503005056801da1: Imputed Rating = 0.6966114031396581
User 44221404 - Skill rgrtuhpx: Imputed Rating = 0.487641379245502
User 44221404 - Skill oorioeyw: Imputed Rating = 0.723128738721662
User 44221404 - Skill dc7f63d82400e4119e54005056801da1: Imputed Rating = 0.43868390579228617
User 44221404 - Skill 4fa5bfaa479de311b77c005056801da1: Imputed Rating = 0.8304254816056329
User 44221404 - Skill 778063d82400e4119e54005056801da1: Imputed Rating = 0.6005572842273066
User 44221404 - Skill cfa6bfaa479de311b77c005056801da1: Imputed Rating = 0.8393749371808592
User 44221404 - Skill ce7f63d82400e4119e54005056801da1: Imputed Rating = 0.6980765332027636
User 44221404 - Skill 9ff8ffd026d943f9b28966fbd0f0691d: Imputed Rating = 0.516608714373624
User 44221404 - Skill 9de3505e73e44b53b63a91cfd6d32e35: Imputed Rating = 0.6108606277665484
User 44221404 - Skill pahghiga: Imputed Rating = 0.6263234801753309
User 44221404 - Skill 7aa6bfaa479de311b77c005056801da1: Imputed Rating = 0.5657480111261072
User 44221404 - Skill 8d7f63d82400e4119e54005056801da1: Imputed Rating = 0.5674614118856385
User 44221404 - Skill 1aa3bfaa479de311b77c005056801da1: Imputed Rating = 0.868471097823924
User 44221404 - Skill b8c908a20a43473aae6f7bb93b37dc9f: Imputed Rating = 0.6902235073181092
User 44221404 - Skill dd9aa9899b2c4cef9369e0c29834931b: Imputed Rating = 0.8136362024655941
User 44221404 - Skill 49706638ba584c7da0d617b27733c4d9: Imputed Rating = 0.7065076069904235
User 44221404 - Skill 51b77d1360c240f087f5f9449ab3b6d8: Imputed Rating = 0.6254428496193946
User 44221404 - Skill 42d543f58969456ab879b84881d40026: Imputed Rating = 0.8212523353807221
User 44221404 - Skill 8ebec51aa39fe3119503005056801da1: Imputed Rating = 0.7570995214270999
User 44221404 - Skill 2aeef1eefabd4c9a858d54a8f06ed435: Imputed Rating = 0.8202042064881898
User 44221404 - Skill 7fa5bfaa479de311b77c005056801da1: Imputed Rating = 0.7323204916304068
User 44221404 - Skill e5a4bfaa479de311b77c005056801da1: Imputed Rating = 0.733038497582764
User 44221404 - Skill a0012eccef86445982a237ddc32bd59f: Imputed Rating = 0.5151368701002549
User 44221404 - Skill tqvayvxt: Imputed Rating = 0.7250783573880188
User 44221404 - Skill 371827581d1742399fb1ef0d95bd35d8: Imputed Rating = 0.7107343850995955
User 44221404 - Skill 3b2fed9dd2b842939972538c0259cf40: Imputed Rating = 0.5023194224612202
User 44221404 - Skill dabec51aa39fe3119503005056801da1: Imputed Rating = 0.27330113940106293
User 44221404 - Skill caa4bfaa479de311b77c005056801da1: Imputed Rating = 0.6333334045043688
User 44221404 - Skill bca6bfaa479de311b77c005056801da1: Imputed Rating = 0.7364059087093752
User 44221404 - Skill 0cb99fc2bb7e4a63af531f863e85cc74: Imputed Rating = 0.9547529884984719
User 44221404 - Skill 84ef902f1b5b4ad688d1453a72f8ae93: Imputed Rating = 0.31860043266600124
User 44221404 - Skill 7dbcc51aa39fe3119503005056801da1: Imputed Rating = 0.7112705285878179
User 44221404 - Skill ef8063d82400e4119e54005056801da1: Imputed Rating = 0.8851964448562383
User 44221404 - Skill 46a4bfaa479de311b77c005056801da1: Imputed Rating = 0.6464563458299198
User 44221404 - Skill a27d63d82400e4119e54005056801da1: Imputed Rating = 0.692611350066119
User 44221404 - Skill bda4bfaa479de311b77c005056801da1: Imputed Rating = 0.7581720625360566
User 44221404 - Skill 78cb9320478e44cc8376830658b89d11: Imputed Rating = 0.7707965081793335
User 44221404 - Skill 31a4bfaa479de311b77c005056801da1: Imputed Rating = 0.5954854566262983
User 44221404 - Skill 8da5bfaa479de311b77c005056801da1: Imputed Rating = 0.7718037951161535
User 44221404 - Skill 02222033a285483493e6aa8077b7e3ca: Imputed Rating = 1
User 44221404 - Skill 6fa4bfaa479de311b77c005056801da1: Imputed Rating = 0.5707711748627108
User 44221404 - Skill a61a9c6250fe42eaae841f899124482c: Imputed Rating = 0.6351937052034724
User 44221404 - Skill fec34ec9c36d48bfb4a353201e36abad: Imputed Rating = 0.6090942790925122
User 44221404 - Skill c6a4bfaa479de311b77c005056801da1: Imputed Rating = 0.6967671985334997
User 44221404 - Skill rooxasha: Imputed Rating = 0.7479234086228644
User 44221404 - Skill 93a4bfaa479de311b77c005056801da1: Imputed Rating = 0.5672386132942139
User 44221404 - Skill c4ecef6364874dc0b140723c7983d3e9: Imputed Rating = 0.518631675499382
User 44221404 - Skill 85a4bfaa479de311b77c005056801da1: Imputed Rating = 0.7954209927186237
User 44221404 - Skill a7680c92eb854c2689ff3aebc2c15a98: Imputed Rating = 0.7082088815720775
User 44221404 - Skill cfbbc51aa39fe3119503005056801da1: Imputed Rating = 0.6260950365833581
User 44221404 - Skill 55a6bfaa479de311b77c005056801da1: Imputed Rating = 0.6559418451256805
User 44221404 - Skill f2a41b48b0ff4134a56182be42992564: Imputed Rating = 0.5865060939609394
User 44221404 - Skill ef7f63d82400e4119e54005056801da1: Imputed Rating = 0.6675735137410534
User 44221404 - Skill 4b5046073c1d47e18936bcf86c1ceb4d: Imputed Rating = 0.5283657304229051
User 44221404 - Skill 7930846efcb3475b9020a0feb3ac94a6: Imputed Rating = 0.7987972620278919
User 44221404 - Skill 3dd15f375dd947199257c58df971d2d4: Imputed Rating = 0.8434485630822404
User 44221404 - Skill fsuuugeh: Imputed Rating = 0.8148620747762628
User 44221404 - Skill 45a3bfaa479de311b77c005056801da1: Imputed Rating = 0.5382183988275774
User 44221404 - Skill e77f63d82400e4119e54005056801da1: Imputed Rating = 0.8673541520700077
User 44221404 - Skill 757f63d82400e4119e54005056801da1: Imputed Rating = 0.3547886472762574
User 44221404 - Skill da7d63d82400e4119e54005056801da1: Imputed Rating = 0.5837999645749622
User 44221404 - Skill fwpljdmd: Imputed Rating = 0.8448132362287815
User 44221404 - Skill cbb5b88ba0b74c0aa420faa822fc66f6: Imputed Rating = 0.8213613589056904
User 44221404 - Skill deebaiyo: Imputed Rating = 0.824182917966042
User 44221404 - Skill 4a9b1e5614a8424d9ac61d2ab08bd4b9: Imputed Rating = 0.7482272223661075
User 44221404 - Skill 5da5bfaa479de311b77c005056801da1: Imputed Rating = 0.574100418893512
User 44221404 - Skill 9134b65b0cd44f7e94639ed849a3790a: Imputed Rating = 0.8703390431698332
User 44221404 - Skill wusiendh: Imputed Rating = 0.6142109489018386
User 44221404 - Skill 49b2b47e3c6740ec87d0e98f6bef58ba: Imputed Rating = 0.9516734600799848
User 44221404 - Skill e1a6bfaa479de311b77c005056801da1: Imputed Rating = 0.6716997150243521
User 44221404 - Skill 5df66e71bed743acb85e5ed1f251c24e: Imputed Rating = 0.7707280579058127
User 44221404 - Skill 08d5c56c53ce4ab0b66eb1ab010a17e1: Imputed Rating = 0.6138245594393477
User 44221404 - Skill d8c6139e6e1d44478db173541f10f04c: Imputed Rating = 0.7784868399557286
User 44221404 - Skill oonmnsot: Imputed Rating = 0.7314194385619456
User 44221404 - Skill 348063d82400e4119e54005056801da1: Imputed Rating = 0.9067249933326793
User 44221404 - Skill 7fb9e2bf81044ff2a3bc2fa95b03154c: Imputed Rating = 0.7359348652587479
User 44221404 - Skill b996b0df157e45b894847e1364c551c4: Imputed Rating = 1
User 44221404 - Skill f7a5bfaa479de311b77c005056801da1: Imputed Rating = 0.3140289361428327
User 44221404 - Skill 65a3bfaa479de311b77c005056801da1: Imputed Rating = 0.6224280365835808
User 44221404 - Skill 68a4bfaa479de311b77c005056801da1: Imputed Rating = 0.7016813474335828
User 44221404 - Skill 35bec51aa39fe3119503005056801da1: Imputed Rating = 0.7489820277887229
User 44221404 - Skill 6888e37abc8c40aea5c43db52ea04817: Imputed Rating = 0.5590603979344961
User 44221404 - Skill 49f705af8e414ded972955d6469f778b: Imputed Rating = 0.8058689825216564
User 44221404 - Skill 838673cb55654be49cd069a189b38b37: Imputed Rating = 0.8226436447119116
User 44221404 - Skill eriecaib: Imputed Rating = 0.7524354502964328
User 44221404 - Skill a4263fbfe2694794a5895caf5a4f4077: Imputed Rating = 0.5426242901505813
User 44221404 - Skill 26e9520539ca4695bc50af9fd35578f9: Imputed Rating = 0.4011408484805259
User 44221404 - Skill c0bec51aa39fe3119503005056801da1: Imputed Rating = 0.8704511166163581
User 44221404 - Skill b7e3216a1040491ebbb37d0aa36407a0: Imputed Rating = 0.7401809818464342
User 44221404 - Skill thookieh: Imputed Rating = 0.467933837489679
User 44221404 - Skill d2a4bfaa479de311b77c005056801da1: Imputed Rating = 0.5896377860185616
User 44221404 - Skill cd2e502a486c4020993a5a346b29698c: Imputed Rating = 0.5175432430072798
User 44221404 - Skill b89a9aa761924619b5d7975f9caa9176: Imputed Rating = 0.7786593463271395
User 44221404 - Skill f3aab89b86fc44a1ada033e2744f50e2: Imputed Rating = 0.8105782961731272
User 44221404 - Skill 0ba5bfaa479de311b77c005056801da1: Imputed Rating = 0.9803213155467502
User 44221404 - Skill 44a4bfaa479de311b77c005056801da1: Imputed Rating = 0.7293791424580147
User 44221404 - Skill 33617132cd15487f9bac830acbf1257e: Imputed Rating = 0.586009890134698
User 44221404 - Skill f5bec51aa39fe3119503005056801da1: Imputed Rating = 0.41395895847921776
User 44221404 - Skill 66a4bfaa479de311b77c005056801da1: Imputed Rating = 0.7315709139101992
User 44221404 - Skill d8e82e84d6d44f2487d6b6dca8cbe77e: Imputed Rating = 0.6087428268495584
User 44221404 - Skill b2a6bfaa479de311b77c005056801da1: Imputed Rating = 0.7625823447434772
User 44221404 - Skill ace4c8b6ebdd4f659a855fff25224ce5: Imputed Rating = 0.831035146547515
User 44221404 - Skill eb9019b48a844fb4b1b81a72a0223ed8: Imputed Rating = 0.9797457836695972
User 44221404 - Skill aebdc51aa39fe3119503005056801da1: Imputed Rating = 0.2451881537936732
User 44221404 - Skill 19bec51aa39fe3119503005056801da1: Imputed Rating = 0.9296984807734582
User 44221404 - Skill nxkecftk: Imputed Rating = 0.504898202466532
User 44221404 - Skill 8eec1c6c87ac4ab289ceaf7f19f3473d: Imputed Rating = 0.8522203363308749
User 44221404 - Skill 0933735398d54740a0349dc331844037: Imputed Rating = 0.7233061771242794
User 44221404 - Skill 3ea4bfaa479de311b77c005056801da1: Imputed Rating = 0.8294051496876773
User 44221404 - Skill 41a4bfaa479de311b77c005056801da1: Imputed Rating = 0.7551294535325505
User 44221404 - Skill 33064db8593c412bbdc636024778a983: Imputed Rating = 0.916388300491001
User 44221404 - Skill 880cb071ff494f1a896eb023ba1df504: Imputed Rating = 0.7746351881373369
User 44221404 - Skill 72a5bfaa479de311b77c005056801da1: Imputed Rating = 0.5899067072606418
User 44221404 - Skill 5fa3bfaa479de311b77c005056801da1: Imputed Rating = 0.4825959863467163
User 44221404 - Skill 224c08fa44af47c3aecb2134ce830ed2: Imputed Rating = 0.7214949938620498
User 44221404 - Skill 47a5bfaa479de311b77c005056801da1: Imputed Rating = 0.6298478248848758
User 44221404 - Skill 8ac5cdeb2a774bf79b20018c930cd64d: Imputed Rating = 0.8986690692478724
User 44221404 - Skill e27f63d82400e4119e54005056801da1: Imputed Rating = 0.7931071672192959
User 44221404 - Skill eaa3bfaa479de311b77c005056801da1: Imputed Rating = 0.5849521323716785
User 44221404 - Skill bba4faf1559c4aaab601ff2a0a414261: Imputed Rating = 0.8301613671122847
User 44221404 - Skill zeiniexe: Imputed Rating = 0.8056582530579758
User 44221404 - Skill b902cb504db24dcf81f261d76a3ee680: Imputed Rating = 0.763430298159501
User 44221404 - Skill ideiyiux: Imputed Rating = 0.765638647851379
User 44221404 - Skill 7237bbd0a9ab4c2f8259fd6c1176a606: Imputed Rating = 0.8077126459754422
User 44221404 - Skill iefeeyuk: Imputed Rating = 0.3632639710433819
User 44221404 - Skill 037f63d82400e4119e54005056801da1: Imputed Rating = 0.8227020524064229
User 44221404 - Skill 938063d82400e4119e54005056801da1: Imputed Rating = 0.8503572434087949
User 44221404 - Skill b309314aa7a9420c90a43f9b6958d3eb: Imputed Rating = 0.8010753013409957
User 44221404 - Skill b6a4bfaa479de311b77c005056801da1: Imputed Rating = 0.9476534579816508
User 44221404 - Skill c80d5a9a4e5940ad9f872b014174d0d5: Imputed Rating = 0.5859385139267169
User 44221404 - Skill a77f63d82400e4119e54005056801da1: Imputed Rating = 0.6084800950548515
User 44221404 - Skill 26bec51aa39fe3119503005056801da1: Imputed Rating = 0.5966110342918202
User 44221404 - Skill 5ebbc51aa39fe3119503005056801da1: Imputed Rating = 0.6243597063897561
User 44221404 - Skill d0a6bfaa479de311b77c005056801da1: Imputed Rating = 0.652446167643721
User 44221404 - Skill 80bdc51aa39fe3119503005056801da1: Imputed Rating = 0.48933675552183564
User 44221404 - Skill 58bbc51aa39fe3119503005056801da1: Imputed Rating = 0.6628137996985013
User 44221404 - Skill b92052ddb2194611b358adc61c68eb09: Imputed Rating = 0.6881194350644505
User 44221404 - Skill 2fa4bfaa479de311b77c005056801da1: Imputed Rating = 0.8019071013365092
User 44221404 - Skill qpcqaxld: Imputed Rating = 0.69587570560643
User 44221404 - Skill ewaerosi: Imputed Rating = 0.7999038111237294
User 44221404 - Skill 5ea4bfaa479de311b77c005056801da1: Imputed Rating = 0.5595975866260734
User 44221404 - Skill a5a3bfaa479de311b77c005056801da1: Imputed Rating = 0.6053483369242422
User 44221404 - Skill 7aa3bfaa479de311b77c005056801da1: Imputed Rating = 0.5108658874940849
User 44221404 - Skill 83a3bfaa479de311b77c005056801da1: Imputed Rating = 0.7462336786477743
User 44221404 - Skill e8bdc51aa39fe3119503005056801da1: Imputed Rating = 0.5758730521355694
User 44221404 - Skill 23bdc51aa39fe3119503005056801da1: Imputed Rating = 0.7055339814418544
User 44221404 - Skill 72567c2874b547f69bca2c23e0833c24: Imputed Rating = 0.693850131473514
User 44221404 - Skill 367e63d82400e4119e54005056801da1: Imputed Rating = 0.6795119608342416
User 44221404 - Skill 71acbbfabd284348b0ac319aff6e0578: Imputed Rating = 0.5379003468578908
User 44221404 - Skill cb5d637ca8284dbea0bbff50c4757549: Imputed Rating = 0.9410514733152477
User 44221404 - Skill 05a4bfaa479de311b77c005056801da1: Imputed Rating = 0.6445796238737053
User 44221404 - Skill 64a5bfaa479de311b77c005056801da1: Imputed Rating = 0.7101311966012258
User 44221404 - Skill 80bbc51aa39fe3119503005056801da1: Imputed Rating = 0.8208245090674429
User 44221404 - Skill 56a3bfaa479de311b77c005056801da1: Imputed Rating = 0.8734438585630762
User 44221404 - Skill 0878db54dfa34859b96ad4ae30711d66: Imputed Rating = 0.3598033274162416
User 44221404 - Skill 3ff21459a3e14fd293eff87f11791e45: Imputed Rating = 0.5913930803181073
User 44221404 - Skill a0a4bfaa479de311b77c005056801da1: Imputed Rating = 0.5587926717759035
User 44221404 - Skill eeb752aa89b44f80af89f18b8f1cbe99: Imputed Rating = 0.5592226636237138
User 44221404 - Skill 297f63d82400e4119e54005056801da1: Imputed Rating = 0.8022534264723558
User 44221404 - Skill nohzooca: Imputed Rating = 0.4238394360494855
User 44221404 - Skill 1ffc95ec4a984a2db57f0f8414ba4165: Imputed Rating = 0.6254929187191853
User 44221404 - Skill e0a3bfaa479de311b77c005056801da1: Imputed Rating = 0.8190945253460622
User 44221404 - Skill 337f63d82400e4119e54005056801da1: Imputed Rating = 0.9687787670503241
User 44221404 - Skill 607f63d82400e4119e54005056801da1: Imputed Rating = 0.3417886245692198
User 44221404 - Skill 00b80d5bd32248069d782629961e9aef: Imputed Rating = 0.6995254092056439
User 44221404 - Skill 641f78171cce4c8d9edcfe98c312fbf7: Imputed Rating = 0.8296156158816507
User 44221404 - Skill 78a4bfaa479de311b77c005056801da1: Imputed Rating = 0.6071633982993986

In [44]:
testset

[(44221404, 'aea3bfaa479de311b77c005056801da1', 0.69336673),
 (39485168, '4aa3bfaa479de311b77c005056801da1', 0.85490263),
 (44230524, '10a4bfaa479de311b77c005056801da1', 0.84845094),
 (39888374, '72a3bfaa479de311b77c005056801da1', 0.97266273),
 (42153241, '70f8d27f8b8f4b6083f4b66fbdb10609', 0.88294154),
 (44864367, 'phaofees', 0.1948475),
 (28387154, 'ee30a13bf08e4880bb4a4ec350837440', 0.59155333),
 (46661482, '5ea3bfaa479de311b77c005056801da1', 0.78478662),
 (31719114, '02a5bfaa479de311b77c005056801da1', 0.48460765),
 (34487757, '6d2bd40241ea4dafb74370433442f1bd', 0.3994852),
 (43681938, 'd3a4bfaa479de311b77c005056801da1', 0.67686767),
 (39905349, 'b7e3216a1040491ebbb37d0aa36407a0', 0.9087594),
 (36126618, '94a5bfaa479de311b77c005056801da1', 0.88590755),
 (35865543, '49a3bfaa479de311b77c005056801da1', 0.983710795),
 (45819022, '9fa3bfaa479de311b77c005056801da1', 0.72504506),
 (31284282, 'b975030e84c74d96a51d4df1fad93ff5', 0.96426828),
 (31722420, '21a4bfaa479de311b77c005056801da1', 0.15225615),
 (44093831, 'bfa4bfaa479de311b77c005056801da1', 1.02119317),
 (31717926, '584d1ed1f674444094abd9f4718a9634', 0.13669864),
 (26589484, '60a3bfaa479de311b77c005056801da1', 0.936372884),
 (43663903, '53a3bfaa479de311b77c005056801da1', 0.869698006),
 (44697263, '97a3bfaa479de311b77c005056801da1', 0.62324269),
 (44446575, '72a3bfaa479de311b77c005056801da1', 0.01270803),
 (42929945, '341598e4a14c4237b7e1187a05cce0a1', 0.3001727),
 (45969281, 'f3a2bfaa479de311b77c005056801da1', 0.1755413),
 (46181745, '05a4bfaa479de311b77c005056801da1', 0.56311917),
 (35961476, '6bec245d5b9e4488b3f58a0d6e271d61', 0.804041366),
 (35376672, '9ca4bfaa479de311b77c005056801da1', 0.544730217),
 (34998844, 'b2a4bfaa479de311b77c005056801da1', 0.97195107),
 (41200875, '55a4bfaa479de311b77c005056801da1', 0.93891547),
 (44714391, '9aa4bfaa479de311b77c005056801da1', 1.12274724),
 (26501086, 'cfe39a065f524b109a54f3f5a3bdc6c1', 0.72820069),
 (40155200, '42a3bfaa479de311b77c005056801da1', 0.93674611),
 (40901667, '3ea3bfaa479de311b77c005056801da1', 0.65861958),
 (45940474, 'd25e0bc526eae311b64a005056801da1', 1.1284256),
 (34161419, '0aaceabece72465f9cf1cd6f93aa90ec', 0.59807255),
 (44119649, '0ae02b76e42f41e3a70a41d2cd44dd45', 0.67194212),
 (45374690, '79a3bfaa479de311b77c005056801da1', -0.07235466),
 (46987055, '5ea4bfaa479de311b77c005056801da1', 0.43140084),
 (44688729, '3ea4bfaa479de311b77c005056801da1', 1.10096771),
 (39323350, '44a4bfaa479de311b77c005056801da1', 0.76061597),
 (41185808, '5cbac51aa39fe3119503005056801da1', 0.95345174),
 (46163947, '72a4bfaa479de311b77c005056801da1', 0.71610746),
 (46641843, '12a5bfaa479de311b77c005056801da1', 0.7336250954),
 (45253627, 'fca2bfaa479de311b77c005056801da1', 0.39198147),
 (44358566, '45a3bfaa479de311b77c005056801da1', 0.59341648),
 (46363100, '4ff273ae5b2240539746cb388a0560a1', -0.0078134),
 (44210324, '60a4bfaa479de311b77c005056801da1', 0.860763916),
 (46276495, '02a3bfaa479de311b77c005056801da1', 0.948405562),
 (45460331, '48a3bfaa479de311b77c005056801da1', 0.38540932),
 (41819478, '0ae02b76e42f41e3a70a41d2cd44dd45', 0.96459),
 (46589326, '25a5bfaa479de311b77c005056801da1', 1.01804064),
 (40187031, '9ca4bfaa479de311b77c005056801da1', 0.6060753),
 (46956187, 'daa4bfaa479de311b77c005056801da1', 0.81053278),
 (45560908, 'd88c7277923544919f499645ff509bd6', 0.39223873),
 (24783919, '5ba4bfaa479de311b77c005056801da1', 0.40675398),
 (31754727, 'xucheipi', -0.00555259),
 (45433589, '58a4bfaa479de311b77c005056801da1', 0.25893717),
 (37709512, 'a9a4bfaa479de311b77c005056801da1', 0.8598503),
 (46161742, '55a4bfaa479de311b77c005056801da1', 1.04030531),
 (38689221, 'dda3108b5fbf4c28afd1fec18e021e7a', 0.551966335),
 (27002433, 'c4772dbe83e44faaaf24ca8b40397511', 0.93311193),
 (43044744, 'b9a3bfaa479de311b77c005056801da1', 0.660250394),
 (44015817, 'c8a4bfaa479de311b77c005056801da1', 0.37822947),
 (45625576, '99a4bfaa479de311b77c005056801da1', 0.45048678),
 (46672520, 'ffa42a4fc57f461a9f71a6e3df4206b4', 0.62629598),
 (44655247, '02a3bfaa479de311b77c005056801da1', 0.9906214392),
 (39043677, '52a4bfaa479de311b77c005056801da1', 1.00172577),
 (45880534, '02a3bfaa479de311b77c005056801da1', 0.9414828),
 (39818637, '5ca84d654a86401784376f57f5c72661', 0.34285727),
 (34888576, 'bea4bfaa479de311b77c005056801da1', 0.64529374),
 (40763042, '3ba3bfaa479de311b77c005056801da1', 1.00988626),
 (45734048, 'cf7e2723d6544dc68edb543eeb893740', 0.33599594),
 (43693994, '08a4bfaa479de311b77c005056801da1', 0.70387304),
 (34464226, 'f4a2bfaa479de311b77c005056801da1', 0.63518047),
 (45140751, '0ea4bfaa479de311b77c005056801da1', 0.8696869),
 (47058314, '4e412280b55e47c8b869591706aa2ea7', 0.67109343),
 (44289821, 'a9a4bfaa479de311b77c005056801da1', 0.29331097),
 (22955767, 'aikaevoy', 0.48766109),
 (47038239, 'bd7b5e8e21eae311b64a005056801da1', 1.01221417),
 (43793073, '63a3bfaa479de311b77c005056801da1', 0.99701408),
 (43153749, 'xafohsha', 0.4385556),
 (44500572, '5a35969ea1ece311b64a005056801da1', 0.90939724),
 (45138219, 'aaa4bfaa479de311b77c005056801da1', 0.97689083),
 (45222954, '38a4bfaa479de311b77c005056801da1', 0.5348559),
 (47403079, '48a3bfaa479de311b77c005056801da1', 0.61826016),
 (43375437, '49a3bfaa479de311b77c005056801da1', 0.96331339),
 (41163536, 'd0a3bfaa479de311b77c005056801da1', 0.27553584),
 (41052439, '59a4bfaa479de311b77c005056801da1', 0.4462517196),
 (45970566, 'fca2bfaa479de311b77c005056801da1', 0.89214319),
 (35377355, '87bac51aa39fe3119503005056801da1', 0.7854877576),
 (46647513, '32a4bfaa479de311b77c005056801da1', 0.16134094),
 (41370343, '34a4bfaa479de311b77c005056801da1', 0.327876545),
 (44269934, '86bcc51aa39fe3119503005056801da1', 0.58434076),
 (40902944, 'd7a4bfaa479de311b77c005056801da1', 0.6595150213),
 (26642125, 'd8bac51aa39fe3119503005056801da1', 0.933726388),
 (44451906, 'fca4bfaa479de311b77c005056801da1', 1.01024623),
 (45296203, '2ca5bfaa479de311b77c005056801da1', 0.78481046),
 (45184428, 'ad8c0c8be0c14a63bf5aedca56c85200', 0.863849399),
 (44823532, '32a3bfaa479de311b77c005056801da1', 0.3066169),
 (44004709, '1ba4bfaa479de311b77c005056801da1', 0.35329208),
 (44622706, '03a3bfaa479de311b77c005056801da1', 0.9777292),
 (42206973, '60a3bfaa479de311b77c005056801da1', 0.799677737),
 (43823497, '83a3bfaa479de311b77c005056801da1', 1.16104294),
 (40084985, '341598e4a14c4237b7e1187a05cce0a1', 0.835731817),
 (46686632, '79817d8de6b049c1b6afecd50c65bf16', 0.45902454),
 (41200075, '1aa5bfaa479de311b77c005056801da1', 0.82903434),
 (44923773, '02a3bfaa479de311b77c005056801da1', 0.964969997),
 (46630233, '18bec51aa39fe3119503005056801da1', 1.00742454),
 (44594359, '1aa3bfaa479de311b77c005056801da1', 0.58954787),
 (36301227, 'f4a2bfaa479de311b77c005056801da1', 0.770465834),
 (33121255, '99a4bfaa479de311b77c005056801da1', 0.666011927),
 (47196276, 'lvniugfv', 1.05540182),
 (46788248, '06a5bfaa479de311b77c005056801da1', 0.51946257),
 (26386531, 'dda3108b5fbf4c28afd1fec18e021e7a', 0.36822556),
 (44545350, 'cd36969ea1ece311b64a005056801da1', 0.76493437),
 (25880903, '3abbc51aa39fe3119503005056801da1', 0.7200972277),
 (42531550, 'eedc6aeb596346819e614ccabd30402b', 0.42098662),
 (45999151, '06a4bfaa479de311b77c005056801da1', 0.09683156),
 (44012321, '65a3bfaa479de311b77c005056801da1', 0.88667911),
 (46234718, '56a4bfaa479de311b77c005056801da1', 1.13780842),
 (45201930, '8aa3bfaa479de311b77c005056801da1', 0.7663982),
 (46086000, 'cbb5b88ba0b74c0aa420faa822fc66f6', 0.8728692023),
 (46101986, 'cbb5b88ba0b74c0aa420faa822fc66f6', 0.880872275),
 (44549806, 'a7a3bfaa479de311b77c005056801da1', 0.49077882),
 (45970381, '3ea5bfaa479de311b77c005056801da1', 1.16180485),
 (39280979, '01a3bfaa479de311b77c005056801da1', 1.04436809),
 (45760604, '02a3bfaa479de311b77c005056801da1', 0.84614942),
 (40172559, '45a3bfaa479de311b77c005056801da1', 0.18099698),
 (44221948, 'dba4bfaa479de311b77c005056801da1', 0.62534939),
 (44123240, '03a3bfaa479de311b77c005056801da1', 1.01160254),
 (44216868, '76a3bfaa479de311b77c005056801da1', 0.79791896),
 (41216696, 'iengohth', 0.10217476),
 (44321133, 'b1a4bfaa479de311b77c005056801da1', 0.755277701),
 (43792478, '99a4bfaa479de311b77c005056801da1', 0.36373577),
 (43623810, 'c3a3bfaa479de311b77c005056801da1', 0.420975664),
 (41617578, '33a3bfaa479de311b77c005056801da1', 0.96449671),
 (37805403, '95a3bfaa479de311b77c005056801da1', 0.88915746),
 (46039007, '287d63d82400e4119e54005056801da1', 0.92585273),
 (40182275, '8ea3bfaa479de311b77c005056801da1', 1.05292865),
 (38177074, 'e2a3bfaa479de311b77c005056801da1', 1.10332871),
 (36119957, 'f27f63d82400e4119e54005056801da1', 0.69247658),
 (31802116, 'b0a3bfaa479de311b77c005056801da1', 0.50052474),
 (35319839, 'ffa42a4fc57f461a9f71a6e3df4206b4', 0.51862054),
 (46551301, 'aaa3bfaa479de311b77c005056801da1', 0.5714056),
 (46171147, 'b2a4bfaa479de311b77c005056801da1', 0.89911734),
 (35375468, 'c6a4bfaa479de311b77c005056801da1', 0.59270605),
 (25660268, '99a4bfaa479de311b77c005056801da1', -0.03173983),
 (44129026, 'b3a3bfaa479de311b77c005056801da1', 1.02407796),
 (39279703, '8e178d664b7f41b8bfe030faeb97a514', 1.10974672),
 (44097230, 'df7d63d82400e4119e54005056801da1', 0.78682393),
 (37972235, '0da4bfaa479de311b77c005056801da1', 0.20041636),
 (30377209, 'a0a4bfaa479de311b77c005056801da1', 0.61020198),
 (46308265, 'fba2bfaa479de311b77c005056801da1', 1.07294173),
 (46335268, 'f3a2bfaa479de311b77c005056801da1', 0.33930877),
 (42131578, '94d01b8e094b46b19ec8adc8e14bc887', 0.14083784),
 (43790870, '4fa3bfaa479de311b77c005056801da1', 0.11685923),
 (44522941, '72a4bfaa479de311b77c005056801da1', 0.54389414),
 (47116754, '72a4bfaa479de311b77c005056801da1', 1.15164003),
 (44895818, '34310c9f27264a42bcd583551d78aee9', 0.786400341),
 (28387158, '24a4bfaa479de311b77c005056801da1', 0.7194013),
 (40493229, '4aa3bfaa479de311b77c005056801da1', 0.97499129),
 (44002809, 'a1a4bfaa479de311b77c005056801da1', 1.14842906),
 (41374218, '27a3bfaa479de311b77c005056801da1', 0.458070842),
 (46719167, '14a4bfaa479de311b77c005056801da1', 0.03376426),
 (44949318, '5ea4bfaa479de311b77c005056801da1', 0.65179849),
 (43811087, '69a3bfaa479de311b77c005056801da1', 0.73211739),
 (39889853, 'afa4bfaa479de311b77c005056801da1', 0.22738356),
 (47181013, '99a4bfaa479de311b77c005056801da1', 0.59525473),
 (43005053, '8a8063d82400e4119e54005056801da1', 0.79363782),
 (45572701, '02a3bfaa479de311b77c005056801da1', 0.99603878),
 (45990899, '52a4bfaa479de311b77c005056801da1', 0.97695314),
 (45855972, 'aaa3bfaa479de311b77c005056801da1', 0.12482996),
 (26584795, 'f3aab89b86fc44a1ada033e2744f50e2', 0.63767985),
 (46628352, '59a4bfaa479de311b77c005056801da1', 0.32842094),
 (46073006, '85cec1c3502d4b1fa0b184152a643466', -0.02826101),
 (44917311, '30c25e6a7c874faea2bbc193320fe60c', 0.65777018),
 (45797495, '6657cdf0c98648a5bfce7b7f6c678eb0', 0.27694617),
 (40111457, 'b773df2a09aa4c51982a9b7806198c28', 0.24605326),
 (39184813, 'faa3bfaa479de311b77c005056801da1', 0.23061678),
 (44549906, '38a4bfaa479de311b77c005056801da1', 0.75236512),
 (36082980, '78a3bfaa479de311b77c005056801da1', 1.00414707),
 (44270314, '17bbc51aa39fe3119503005056801da1', 1.13962534),
 (45478425, 'b9a3bfaa479de311b77c005056801da1', 0.65872079),
 (44093887, 'bea3bfaa479de311b77c005056801da1', 0.32157645),
 (42890224, 'b7e3216a1040491ebbb37d0aa36407a0', 0.33079723),
 (17867751, 'rgrtuhpx', 0.15394216),
 (34826518, 'ffa2bfaa479de311b77c005056801da1', 0.59516853),
 (36356401, 'c0a4bfaa479de311b77c005056801da1', 1.1268876),
 (36318818, '02a3bfaa479de311b77c005056801da1', 0.9194656004),
 (45119113, 'aeece3c317674ff390f3626eaafbdca4', 0.53388013),
 (44541668, '4e629d483deb47b5bcc50a50783261f8', 0.756607559),
 (43793029, 'a4a3bfaa479de311b77c005056801da1', 0.83557616),
 (46814184, '67a4bfaa479de311b77c005056801da1', 0.05867393),
 (39750035, '76a3bfaa479de311b77c005056801da1', 1.0241289),
 (43631110, '0ae02b76e42f41e3a70a41d2cd44dd45', 0.35529725),
 (46662586, 'd777a702fd9b4308bb4fb399aaf6778a', 0.91320727),
 (44426638, 'fca2bfaa479de311b77c005056801da1', 0.9356087),
 (44872904, 'ouchotha', 0.73567426),
 (11922221, '85cec1c3502d4b1fa0b184152a643466', 0.31935128),
 (40148247, '44a4bfaa479de311b77c005056801da1', 0.56244502),
 (45753700, 'eighaich', 1.15543487),
 (46033467, '735f12e14b3d42eb86dc02816aba0cf8', 1.16840974),
 (40803033, '74a3bfaa479de311b77c005056801da1', 0.43722383),
 (46488494, 'fba2bfaa479de311b77c005056801da1', -0.04498375),
 (46804075, '28a3bfaa479de311b77c005056801da1', 0.9963832),
 (45639454, '01a3bfaa479de311b77c005056801da1', 0.67299789),
 (46710034, 'b3a3bfaa479de311b77c005056801da1', 0.49322871),
 (42571158, '78a3bfaa479de311b77c005056801da1', -0.0038229),
 (38711122, '02a3bfaa479de311b77c005056801da1', 0.990369004),
 (44388974, '40bac51aa39fe3119503005056801da1', 0.95940947),
 (45304614, '02a3bfaa479de311b77c005056801da1', 1.0235298),
 (38496059, '8e30d138f63c4545884966ef4c650f16', 0.97801095),
 (44076648, '46a3bfaa479de311b77c005056801da1', 1.06539396),
 (45740610, '46a3bfaa479de311b77c005056801da1', 0.9650953386),
 (33397647, '6da5bfaa479de311b77c005056801da1', 0.86620286),
 (45780110, '67a5bfaa479de311b77c005056801da1', 0.60233017),
 (44564711, '42a3bfaa479de311b77c005056801da1', 0.59070905),
 (36553881, '67a5bfaa479de311b77c005056801da1', 0.78857298),
 (35377103, '9aa4bfaa479de311b77c005056801da1', 0.8306814),
 (44827212, 'd8fee786101848e581e2bb2403e9825a', 0.63424406),
 (44269686, '64bac51aa39fe3119503005056801da1', 0.9718136),
 (33082787, '6d2bd40241ea4dafb74370433442f1bd', 0.42653298),
 (34700751, 'b7a3bfaa479de311b77c005056801da1', 1.05354108),
 (44111616, 'a9a4bfaa479de311b77c005056801da1', 1.0673945),
 (35951524, 'ffa42a4fc57f461a9f71a6e3df4206b4', 0.69061322),
 (45006594, '14a4bfaa479de311b77c005056801da1', 1.02499513),
 (25292737, '56a3bfaa479de311b77c005056801da1', 1.05857613),
 (33826720, 'a1a4bfaa479de311b77c005056801da1', 0.47205055),
 (46049015, '56a4bfaa479de311b77c005056801da1', 0.71252604),
 (45033572, 'cca3bfaa479de311b77c005056801da1', 0.89316102),
 (39215262, 'cbb5b88ba0b74c0aa420faa822fc66f6', 0.92094548),
 (34994982, '44a3bfaa479de311b77c005056801da1', 0.6510655),
 (36679222, '90e94931b98b47799950dd93c9a8dc28', 0.94040756),
 (45119026, 'eea4bfaa479de311b77c005056801da1', 0.28095384),
 (42717106, 'ffa5bfaa479de311b77c005056801da1', 0.57910718),
 (45355335, '4ca5bfaa479de311b77c005056801da1', -0.151521),
 (44002165, '94dae4aa0077458e8f01fbe1bace042b', 0.33677184),
 (38801868, '5e07fc9fef154c76a81b8755c84ce4cc', 1.19460985),
 (42738648, '2ba5bfaa479de311b77c005056801da1', 0.87621181),
 (45448688, 'a3a4bfaa479de311b77c005056801da1', 0.44600202),
 (46188724, '1aa5bfaa479de311b77c005056801da1', 0.98983178),
 (43213104, '55a3bfaa479de311b77c005056801da1', 0.47167133),
 (43046805, 'a9a4bfaa479de311b77c005056801da1', 0.88958943),
 (44994534, '2ea4bfaa479de311b77c005056801da1', 0.85900962),
 (44451910, 'fca4bfaa479de311b77c005056801da1', 0.64630025),
 (45166722, 'f5a4bfaa479de311b77c005056801da1', 0.62940894),
 (35944502, '9fa4bfaa479de311b77c005056801da1', 0.81200934),
 (44128073, '47a3bfaa479de311b77c005056801da1', 0.70641837),
 (26653620, '77a3bfaa479de311b77c005056801da1', 0.824553281),
 (45018090, '5dbbc51aa39fe3119503005056801da1', 0.49518937),
 (44864881, '6aa5bfaa479de311b77c005056801da1', -0.15641555),
 (34636467, '24bcc51aa39fe3119503005056801da1', 0.22988614),
 (44216632, '0469dceb9ab14c00a80d96f707af4f8f', 0.713845389),
 (46162004, '1abdc51aa39fe3119503005056801da1', 0.90753883),
 (45157225, 'e0a4bfaa479de311b77c005056801da1', 0.27350633),
 (26637154, '9cc61e8eb0d24540a43ca6bf40cd25ec', 0.91379233),
 (45435219, 'b3a3bfaa479de311b77c005056801da1', 0.99343618),
 (47184551, '4ea3bfaa479de311b77c005056801da1', 0.97390202),
 (46065903, 'aca4bfaa479de311b77c005056801da1', 1.0567006),
 (45299165, 'cca4bfaa479de311b77c005056801da1', 0.531403175),
 (46858925, '4dbcc51aa39fe3119503005056801da1', -0.01567912),
 (41125309, '090e3de89d3f4f9a81e60fb992b655d3', 0.557104522),
 (26634105, '86bcc51aa39fe3119503005056801da1', 1.12847372),
 (47062000, '56c13db64f7746bbad0fe35092c4ad81', 0.99440103),
 (40405439, 'bea4bfaa479de311b77c005056801da1', 0.588120107),
 (45204181, '9de3505e73e44b53b63a91cfd6d32e35', 1.00632033),
 (46507094, '090e3de89d3f4f9a81e60fb992b655d3', 0.59604663),
 (39217181, 'c3a3bfaa479de311b77c005056801da1', 0.751182779),
 (39290053, '76a3bfaa479de311b77c005056801da1', 0.3491498),
 (46254460, '79817d8de6b049c1b6afecd50c65bf16', 0.87198755),
 (39806615, '4c66ef8ca5164a278f28c0548a75bee4', 0.71112971),
 (33825091, '62a3bfaa479de311b77c005056801da1', 0.52061498),
 (45539684, '7ca4912b6987425caa511aaf8a31e3a7', 0.8383298),
 (45845537, '02a5bfaa479de311b77c005056801da1', 0.66056123),
 (35546934, '69a3bfaa479de311b77c005056801da1', 0.3864029),
 (46681014, '96a3bfaa479de311b77c005056801da1', 0.774831536),
 (42865129, '67a5bfaa479de311b77c005056801da1', 0.1798409),
 (30524797, 'dda3108b5fbf4c28afd1fec18e021e7a', 0.68707348),
 (45774553, '4c66ef8ca5164a278f28c0548a75bee4', -0.23572248),
 (34430191, '5aa3bfaa479de311b77c005056801da1', -0.13818308),
 (44317403, '58a4bfaa479de311b77c005056801da1', 0.5239822),
 (44329129, '44a3bfaa479de311b77c005056801da1', 0.90468304),
 (43827649, '47a3bfaa479de311b77c005056801da1', 0.8076015),
 (40155692, 'b0a3bfaa479de311b77c005056801da1', 0.585214314),
 (40549221, 'a4a3bfaa479de311b77c005056801da1', 0.58788978),
 (44596619, '02bec51aa39fe3119503005056801da1', 0.97639437),
 (44866319, '35a3bfaa479de311b77c005056801da1', 0.9623923),
 (40155538, '36546a4555154a3881ff249a7608d3ab', 0.825489815),
 (43708830, '2ba5bfaa479de311b77c005056801da1', 0.68621545),
 (35550562, '9de3505e73e44b53b63a91cfd6d32e35', 0.72445453),
 (39158207, '377e63d82400e4119e54005056801da1', 0.11576564),
 (44599070, '8ba5bfaa479de311b77c005056801da1', -0.36183352),
 (44526936, 'fea2bfaa479de311b77c005056801da1', 0.4093994),
 (46060958, '85afef75aa05478f8b25f9747875998c', 0.83248596),
 (46169986, '97a3bfaa479de311b77c005056801da1', 0.53243862),
 (26659258, 'c3a3bfaa479de311b77c005056801da1', 0.90208304),
 (47331998, '67a4bfaa479de311b77c005056801da1', 0.948223569),
 (47076577, 'fca2bfaa479de311b77c005056801da1', 0.83731601),
 (44087169, '02a3bfaa479de311b77c005056801da1', 1.03958349),
 (40983747, '4aa3bfaa479de311b77c005056801da1', 0.70311101),
 (41131475, 'a0e0d4a607b949bd81944429da6b3cdf', 0.3133247),
 (44832247, '3ea3bfaa479de311b77c005056801da1', 1.06640146),
 (26617643, '8883989384534e89b8fe97ecb216a150', 1.11463174),
 (44269076, 'ac2136f312fe4e67b5280f6a26e6a20a', 0.919267804),
 (43626721, '99a4bfaa479de311b77c005056801da1', 0.91294431),
 (47090643, 'df7d63d82400e4119e54005056801da1', 1.1198159),
 (40257908, '02a3bfaa479de311b77c005056801da1', 1.0053707),
 (35131980, '44a3bfaa479de311b77c005056801da1', 0.39899573),
 (32381317, 'e9a3bfaa479de311b77c005056801da1', 0.15700945),
 (44440021, 'fca2bfaa479de311b77c005056801da1', 0.90669228),
 (43741643, '6d2bd40241ea4dafb74370433442f1bd', 1.14515076),
 (36371756, '56a4bfaa479de311b77c005056801da1', 0.8928373),
 (35184927, 'fea2bfaa479de311b77c005056801da1', 0.71023828),
 (44122561, 'aba3bfaa479de311b77c005056801da1', 0.472716945),
 (26589709, 'aaa3bfaa479de311b77c005056801da1', 0.38620435),
 (45501350, '87bac51aa39fe3119503005056801da1', 0.82983891),
 (45237353, '4ca4bfaa479de311b77c005056801da1', 0.8027282294),
 (44217565, 'bbb33d43db4744c2ac05a97ac81154f3', 0.37815535),
 (39984656, '3e9ea21f01934da99619d6cd113179f0', 1.13428576),
 (47079888, '3ca3bfaa479de311b77c005056801da1', 0.45964195),
 (36017072, '00bec51aa39fe3119503005056801da1', 0.91544003),
 (35463684, 'cbb5b88ba0b74c0aa420faa822fc66f6', 1.07638219),
 (40102945, '8e051784e51f413d83565054be4123d6', 0.78854535),
 (46217271, '96a3bfaa479de311b77c005056801da1', 0.83692194),
 (22955410, '65a3bfaa479de311b77c005056801da1', 0.06799394),
 (45378980, 'e7a3bfaa479de311b77c005056801da1', 0.12681086),
 (42113376, '5a8052f451ed4f08a532522eed652ce9', 0.52849697),
 (45157607, '3ea3bfaa479de311b77c005056801da1', 0.99788889),
 (45873596, 'a7a3bfaa479de311b77c005056801da1', 0.42514554),
 (33021608, 'fea2bfaa479de311b77c005056801da1', 0.0322276),